### ISSUE TITLE
NTR: inferred from text mining (ITM)

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#100]
For HPO annotations we use ITM, I always assumed this was in ECO, but it seems not. Can we have this?

cc @drseb @mbrush @DoctorBud

**Comment by rctauber** [comment]
It looks like there was some talk about this in tracker issue #66 (debate about assertion or evidence), but it doesn't look like it was resolved.

There is the class '**author statement**' under evidence. Perhaps '**author statement from text mining**' or '**author statement inferred from text mining**' would be logical? Though it might fit better under '**traceable author statement**', since you would have a known/cited reference... Would love some thoughts on this!

**Comment by pnrobinson** [comment]
This isn't really an author statement, since in many cases, a humanbeing will never have personally examined the results of text mining. The HPO was using both IEA for "guided text mining" (an extremely accurate mining that exploited structures in dociments) and ITM (for traditional mining from free text). Does that make any sense?

**Comment by mchibucos** [comment]
I have some thoughts on what people have said so far:

Regarding #66, @rctauber I emailed the author of that term request. She has moved on and no longer requests this term. I haven't updated the ticket yet, and I might migrate this issue, as we still could stand to make this and some related terms.

I agree with @rctauber that a term for 'author statement from text mining' might be useful - if author statements were the evidence being text mined - but there are many other types of evidence that could be gotten via text mining, as well. Regarding 'combinatorial evidence' terms, I think those are really about combining evidences to draw a larger picture that isn't possible by constituent evidence types. Although text mining may be mentioned in the comment, it should not be considered as a single evidence type for this term, so it is inappropriate here.

I agree with @pnrobinson that ITM is not an author statement, but to be clear, I believe that in ECO we could actually have an author statement that is not personally examined by a person. Author statements could be gotten via text mining. [We must distinguish between the statement printed in the literature and the means by which it is extracted/interpreted.] At present we only have a term for 'author statement used in manual assertion' (ECO:0000302). We do not have the counterpart for 'author statement used in automatic assertion', likely because most of the annotation is being done by biocurators manually reading the literature. But if it is possible to computationally extract an author statement and then make an annotation based on that statement, then I'd say it is possible for us to have such a term. In fact, I think that very soon we need to revisit the 'assertion method' node, and I have been considering how techniques like text mining fit into this...

**Comment by rctauber** [comment]
#106 includes a request for ITM from HPO - going to close this issue to consolidate discussion on one thread.
