### ISSUE TITLE
Evidence codes for HPO

### ISSUE THREAD

**Issue by pnrobinson** [evidenceontology/evidenceontology#106]
When the Human Phenotype Ontology started, we did a few things in-house that we would now like to make more compatible with OBO standards. 
ECO has IEA and TAS, but we need terms for ITM, PCS, and ICE defined as below (see http://human-phenotype-ontology.github.io/documentation.html#annot).
thanks

Evidence code: This required field indicates the level of evidence supporting the annotation. At the kickoff of the HPO, most annotations were extracted by parsing the Clinical Features sections of the omim.txt file. These annotations are assigned the evidence code “IEA” (inferred from electronic annotation). Other codes include “PCS” for published clinical study. This should be used for information extracted from articles in the medical literature. Generally, annotations of this type will include the pubmed id of the published study in the DB:Reference field. Finally, “ICE” can be used for annotations based on individual clinical experience. This may be appropriate for disorders with a limited amount of published data. This must be accompanied by an entry in the DB:Reference field denoting the individual or center performing the annotation together with an identifier. For instance, GH:007 might be used to refer to the seventh such annotation made by a specialist from Gotham Hospital. (assuming the prefix GH has been registered with the HPO). We have also included “ITM” to mark annotations retrieved by text-mining (inferred by text-mining). Finally we have TAS, which stands for “traceable author statement”, usually reviews or disease entries (e.g. OMIM) that only refers to the original publication.

**Comment by mchibucos** [comment]
Thanks @pnrobinson for the requests! We will discuss this and reply shortly.

**Comment by pnrobinson** [comment]
@mbrush can you take a look at these terms please?

**Comment by mbrush** [comment]
Can I assume that the PCS and ICE terms are non-controversial, given the lack of challenge or discussion around the proposed definitions, and can be implemented fairly soon?  My thoughts on the third requested term, ITM, are below.

In #100 @mchibucos suggests that this term would map to an 'author statement used in automatic assertion'  in ECO. This makes sense if we assume that that all text-mined annotations are based on an underlying author statement of the fact captured in the annotation.  However, this may not always be the case - a text-mining tool might make an annotation such as _"phenotype X is part of disease Y"_ based only on a co-occurrence of these terms in text, and not an actual assertion of this fact by the author. If this is the case, you could argue that there is no underlying author statement representing supporting evidence for the annotation - so  'author statement used in automatic assertion' would not be appropriate.  Rather, what we have is a **text-mining agent** making an **inference** from text.  
 
@pnrobinson or  @cmungall  can you confirm that this is the case for some HPO annotations? 
 
If this _is_ the case, then ITM may better be represented  by a new term that is not linked to an author statement.  I would suggest one that might live in the 'inferential evidence' branch of ECO. I see a 'curator inference' term here that might reasonably be paralleled by a sibling class such as 'software agent inference', and under this class we could create a term for a text-mining inference.  Or it may be that the current sibling of 'curator inference', 'evidence based on computational logical inference', is meant to represent this notion of a 'software agent inference', and the requested text-mining inference term could be placed under this class.
 
![eco](https://cloud.githubusercontent.com/assets/5184212/19977683/9e561470-a1b1-11e6-8eef-42aaaac3110e.jpg)


 @mchibucos and @rctauber, if peter and chris confirm my assumption above, does this solution sound reasonable?

**Comment by pnrobinson** [comment]
Hi Matt,
Our use case is that we did two types of text mining -- one was from a semi structured text and was essentially 99% accurate, and the other was from narrative text and was about 70% accurate. We used the code IEA (inferrence from electronic annotation) for the first, and ITM (inferred from text mining for the second). This corresponds to "evidence used in automatic assertion" in ECO. I have to admit I do not understand the definition of that term in ECO at all and I would suggest that there is substantial overlap with "inferential evidence" -- I hope I am not being daft but I would suggest revisiting these terms and making the definition more easily comprehensible (or adding a comment with some further explanations).
Writing this, I realize that the two terms we were using at HPO are very ad hoc and it might not be good to try to include them in exactly the same form. However, there are various degrees of "concept recognition" using various types of algorithms with various degrees of accuracy, and it would be useful to capture at least some of theis in ECO
For me the logical structure would be
-- inferred based on computational concept recognition
---- inferred based on concept matching from structured document
---- inferred based on concept recognition in narrative text
---- inferred based on text mining in free text

(It might be good to consult with a text mining expert about the number of terms and the best way to name them if you agree with this suggestion!)

**Comment by mbrush** [comment]
Update: @pnrobinson decided to hold off on the ITM term for now - so we only need classes for the PCS and ICE codes.  

@mchibucos and @rctauber - can we get those in soon?  I made a more detailed proposal below - let me know if you need more from us to make this happen.  Thanks!

----

**PCS (Published Clinical Study):**  Seems fairly straightforward to subtype this under the ECO 'traceable author statement' class. Proposed metadata below.
 
    PARENT ECO CLASS:  ECO_0000033 ! traceable author statement
    LABEL: traceable author statement from published clinical study
    DEFINITION: a traceable author statement that is based on a publication about a clinical study.
    SYNONYM: published clinical study evidence
    SYNONYM: PCS
    COMMENT: Created and used by the Human Phenotype Ontology (HPO) Annotations group. Here it is used when evidence for an HPO annotation is information extracted from articles in the medical literature. 
 
 ----

**ICE (Inferred from Clinical Experience):** Placement of this term in ECO may require some discussion.  I think its currently fits best under 'curator inference'  - as the clinician is playing the role of a curator in making the annotation based on his/her clinical experience. Proposing this term below as a sibling of 'inference from background scientific knowledge', although depending on how this is interpreted it could be a subclass of this term.  
 
    PARENT ECO CLASS:  ECO_0000205 ! curator inference?
    LABEL: inference based on individual clinical experience 
    DEFINITION: a curator inference that is based on the individual clinical experience of a clinician 
    SYNONYM: individual clinical experience evidence
    SYNONYM: ICE
    COMMENT: Created and used by the Human Phenotype Ontology (HPO) Annotations group. Here it is used for annotating disorders with a limited amount of published data, and is accompanied by a reference to the individual or center performing the annotation.

----

Note that the closed ticket #32 holds older discussions about the need for three letter codes for the HPO project.

**Comment by pnrobinson** [comment]
Thanks, Matt, I agree completely with these suggestions which would be useful for our work!

**Comment by rctauber** [comment]
@mbrush @pnrobinson Would you consider the three-letter codes to be exact synonyms for the classes, or for their child classes which are '... used in manual assertion' (like the GO code mappings)? Then the manual assertion versions would be used for annotations.

**Comment by mchibucos** [comment]
The three-letter code are synonyms to the manual assertion subclasses. This is the precedent agreed upon by GO, UniProt, and related resources. If you are seeking compatibility, then this is how you should do it. However, there are some new proposals that arose at GO this weekend with respect to mappings. I will comment on this after I comb through my notes.

**Comment by pnrobinson** [comment]
Not sure I understand the question. The three letter code ICE is an exact synonym for "inference based on individual clinical experience" but (of course) it cannot be an exact synonym for child classes if the child class has some differentiating characteristic. I don't think I understand the question

**Comment by mbrush** [comment]
@pnrobinson - ECO has the convention of implementing subclasses for many terms that specify if the evidence is used in a manual or automatic assertion.   e.g. 
 
sequence similarity evidence
--sequence similarity evidence used in manual assertion
--sequence similarity evidence used in automatic assertion
 
I think Marcus is saying that most efforts that use ECO in annotations apply these more specific terms. And the historic GO codes such as  'ISS' ('inferred from sequence similarity') are mapped to these more specific ECO terms that specify use in a manual annotation (e.g. 'sequence similarity evidence _used in automatic assertion_')  rather than the more generic parent (e.g. 'sequence similarity evidence').
 
So the question from Marcus is whether we want to follow this convention for the two new terms needed for HPO - i.e. create classes for 'traceable author statement from published clinical study _used in manual assertion_' and 'inference based on individual clinical experience _used in manual assertion_', and apply the PCS and ICE synonyms on these terms, which would be the ones used in WebPhenote. 
 
Notably, the TAS code (which WebPhenote is also using) is mapped to ECO:0000304 ! 'traceable author statement used in manual assertion' (as opposed  to its parent 'traceable author statement').  So there is precedent here. Ultimately it matters only insomuch as we should try to follow conventions used by our forbearers where they exist - which Marcus suggests is the case here?  But from WebPhenote perspective it would make no difference.

**Comment by mchibucos** [comment]
@mbrush beat me to the punch. Was replying as this came in. I'll give my full reply anyway:

@pnrobinson the question that @rctauber was asking had to do with ECO's structure as it relates to vocabularies at other resources. Yes, obviously ICE is an exact synonym for whatever you define it to be, so in this "inference based on individual clinical experience". But she was intending to say, should your ICE term map to an ECO term called something like "individual clinical experience evidence" OR "individual clinical experience used in manual assertion"?

Background on why she asked: Five years ago ECO started distinguishing between "evidence" and "evidence used in [manual or automatic] assertion". This arose out of issues concerning computational analysis as they were represented by the GO (who originally created ECO before I took it over). GO has the IEA code that says that a particular annotation arose from an automatic process such as a pipeline and importantly it was not manually reviewed. The problem with IEA is that it is lossy - it doesn't say anything about the actual type of thing that was done, only how the annotation was made. So to address this we instituted a semi-solution (not a fix, because this has its own problems) where we created a second root class in ECO, 'assertion method' and IEA became a subclass called 'automatic assertion'. We then created combinatorial classes of the pattern "evidence used_in assertion method".

So now if, for example, one annotates a protein using a BLAST search and manually reviews the result, they could use the ECO term ECO:0000030 'BLAST evidence used in manual assertion' to represent the evidence. If, however, the BLAST evidence was not manually reviewed, then one could use ECO:0000209 'BLAST evidence used in automatic assertion'. This solution has given us the ability to go much further than IEA with computational annotation evidence.

So Becky was asking you should your term map to one of the combinatorial evidence terms or a pure evidence term. The precedent established by GO is to map to the combinatorial term. For example, the GO code "EXP" maps to ECO:0000269 'experimental evidence used in manual assertion' and _not_ ECO:0000006 'experimental evidence'. Check out the file created by @cmungall https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt for such mappings to GO.

Now all that being said, here are some issues with this 'fix'. 1. the defs are currently Aristotelian, which means that the "...used in assertion" terms are pretty uninformative and curators have to look at the "evidence" parent classes to understand the defined evidence part. 2. Because it was implemented by GO/UniProt GOA initially, and we have added terms on an as needed basis, the coverage of combinatorial terms is very incomplete, and most terms do not have this. 3. There is user confusion [justifiably] because this solution is not well known enough - we need to increase user awareness and have better documentation (in progress). 4. Because most of the experimental techniques are not necessarily things that would be done in an automatic fashion, it might make sense to drop this as a broad solution and only adopt this for the computational side of things. This last issue was a topic of discussion at GO this weekend...

Anyway, that's the background and my attempt to bring everyone new to this up to speed. Sorry if there is any lingering confusion. If so, please explain/ask, because these types of concerns are helping us better document and come up with strategies for all of our users...

**Comment by mchibucos** [comment]
@mbrush yes, you correctly captured the essence of my thoughts. Thank you.

**Comment by rctauber** [comment]
Sorry for that unclear question - the wording was a little confusing now that I look back at it! @pnrobinson (and thank you for the clarification @mbrush @mchibucos )

**Comment by pnrobinson** [comment]
Hi!
I agree that "...use in manual/automatic assertion are useful child terms. This would apply to our work
TAS
-- automatic (would be our IEA)
-- manual (would be our TAS, published clinical studies)
Publised Clinical Study
-- automatic (we are not doing this yet for rare disease)
manual -- our PCS

Individual clinical experience probably *has to* be manual, unless we figure out a way of automatically reading clinician's minds...

**Comment by rctauber** [comment]
Hi again @pnrobinson -
Here are the added terms... I did not add in the automatic assertion term for PCS but please let me know if you need it. If these look good, I'll mark this issue as closed. I included the comments for the manual assertion terms, along with a rdfs:seeAlso to the documentation. Thanks!

ECO:0006016 ! 'traceable author statement from published clinical study'
definition: A type of traceable author statement that is based on a publication about a clinical study.
synonym: published clinical study evidence

ECO:0006017 ! 'traceable author statement from published clinical study used in manual assertion'
definition: A type of traceable author statement from published clinical study that is used in a manual assertion.
synonym: PCS (HPO)

ECO:0006018 ! 'inference from individual clinical experience'
definition: A type of curator inference that is based on the individual clinical experience of a clinician
synonym: individual clinical experience evidence

ECO:0006019 ! 'inference from individual clinical experience used in manual assertion'
definition: A type of inference from individual clinical experience that is used in a manual assertion.
synonym: ICE (HPO)

**Comment by pnrobinson** [comment]
Thanks, these terms are useful for us!
I agree that ECO:0006017 = our old PCS
and
ECO:0006019 = our old ICE

**Comment by rctauber** [comment]
Hi @pnrobinson !
I'd like to reopen this issue, as we are doing some addition of terms to the 'traceable author statement' node for the Disease Ontology.

We are adding 'traceable author statement from journal publication'. After some discussion, we are hoping to have this be a childless term. But, it wouldn't make sense for PCS to be anything but a child of this term. We discussed merging PCS ('traceable author statement from published clinical study') into this new term, and including it as a narrow synonym.

Alternatively, we could rename the current PCS term to be 'traceable author statement from journal publication' and still include it as a narrow synonym, then we could recycle the ID. 

Would this be alright for the HPO annotations, or would it cause problems?
Thanks!

CC @lschriml

**Comment by pnrobinson** [comment]
I thought that traceable author statement is used if the biocurator is referring to a review in which the actual publication that supports an assertion is cited (but the biocurator did not check the original article). Our use of PCS means that the data are directly derived from the referenced publication. Can we discuss the definitions of the proposed terms? Also, given the use of TAS by the gene ontology (which is similar to our use), I do not think that the label is that great there is a risk of confusion.

**Comment by rctauber** [comment]
Thanks for the fast response @pnrobinson ...
We definitely still have some work to do on sorting out where this best fits into ECO, as you point out that TAS was created for a very specific use case. Before we move farther, I just wanted to double check, is the current placement of PCS under TAS accurate?

**Comment by mchibucos** [comment]
@rctauber Is the ongoing discussion being tracked anywhere, such as DO tracker?
I agree with @pnrobinson that TAS is used to refer to a citable source; but I'd like to clarify by adding that it says nothing about whether the biocurator checked the original article - only whether the statement could, in theory, be traced to another source. (Contrast that with NAS, which is to support a statement not attributable to a source.)

I agree also that this needs to be discussed (more broadly) and could add to confusion.
I do not see how a published study itself can be construed as an author statement. Something is amiss.

**Comment by pnrobinson** [comment]
My assumption is that if the biocurator has consulted the original source, then he or she would cite that in preference to a review article, but I agree that this is not part of the definition of TAS. 
I would say that PCS could be a child of TAS, but could just as well be a sibling. The overall parent could/should be published assertion, and there are various child terms that specify what kind of published assertion, including TAS, NAS, PCS, and others as needed. It would also be OK to have something like PAS for published author assertion, meaning a direct assertion in a publication (as opposed to a second hand assertion via TAS or an assertion by way of a review article that states an option, i.e., NAS).

**Comment by rctauber** [comment]
@pnrobinson - We were guided by the original placement of PCS, but we think your suggestion is accurate. In light of this, we are going to revisit the placement of PCS as a sibling, rather than child, of TAS - and creation of a parent class.

@mchibucos & @pnrobinson - I'd love to move the discussion to the new issue #158
Thanks for all your input!

**Comment by mchibucos** [comment]
Yes, @pnrobinson you are correct about TAS and how it is used. I just wanted to clarify that formally (in the definition) there is no _requirement_ for a curator to not verify the original source. But the way that it has been used, that is typically the assumption.

@rctauber Sounds good to move to #158. Thank you!

**Comment by pnrobinson** [comment]
@rctauber OK to move to #158, I am closing this
