### ISSUE TITLE
Make a derived mapping file

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#116]
This subsumes #111 

We will make a derived version of http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt

this will be called

http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt

we will infer for the subclass closure. It will then be a simple direct lookup in either direction

cc @loricorbani @mchibucos @ukemi

**Comment by cmungall** [comment]
@mchibucos is this something someone on your side can work on

**Comment by mchibucos** [comment]
yes. we'll discuss at our group meeting today.

**Comment by mchibucos** [comment]
@rctauber will add a query to create this file, and we will tie this into our release process, so it is automated. (@nsuvarnairi)

**Comment by loricorbani** [comment]
Rebecca, will this be the url you want me to use to grab the file?  we will probably be grabbing the file weekly, if not daily, to pick up any changes to the evidence ontology.

Or will this be copied to another area for picking up?

https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt

**Comment by tberardini** [comment]
@lreiser: this one as well

**Comment by loricorbani** [comment]
this file as ctrl-M (mac) when I download it as raw.  Is this intentional?  I  can convert it...but wanted to ask.  Thanks.

**Comment by rctauber** [comment]
@loricorbani That's strange - it may be because I auto-generated it. I just had to update a mapping and I did it manually, so try now and see if it's any different?

**Comment by loricorbani** [comment]
still getting the same issue.

**Comment by rctauber** [comment]
@loricorbani check now - I added in a newline character and tested on my PC at home. Seemed to download fine there now.

**Comment by loricorbani** [comment]
there is still a ^M at the end of each row, in addition to a newline

**Comment by tonysawfordebi** [comment]
I've been comparing the mappings in gaf-eco-mapping-derived.txt with the mappings that my script generates, and I've noticed that there are a handful of differences / ambiguities which make me wonder whether the structure of the ECO graph might need a bit of tweaking.

In gaf-eco-mapping-derived.txt, ECO:0000284 (and its descendants ECO:0000280-283) are mapped to IEP, while my script maps them to IDA. This is because ECO:0000280 is_a ECO:0000270 (IEP) *and* is_a ECO:314 (IDA).

In the file, ECO:0001170 is mapped to IPI, while I have it mapped to IDA. This is because ECO:1170 is_a ECO:314 (IDA) *and* is_a ECO:353 (IPI). A similar IDA vs IPI ambiguity applies to ECO:0005640.

Finally, ECO:0005601 is mapped in the file to ECO:314 (IDA), while my script maps it to ECO:269 (EXP). This is a slightly different case from the others, because there is a route through the graph from ECO:5601 to both ECO:314 and ECO:269, but the one to ECO:269 is shorter.

**Comment by rctauber** [comment]
Hi @tonysawfordebi -

It looks like ECO:0000284 is a child of a term with multiple inheritance, as with ECO:0001170... Both of these terms are 'protein assay evidence' children, which is IDA (at least, the manual assertion term is a child of 'direct assay evidence used in manual assertion'). The other parents are IEP and IPI, respectively. It seems that the more-specific mappings for these terms make sense ('protein expression evidence used in manual assertion' = IEP and 'cross-linking evidence used in manual assertion' = IPI). If these are not correct, though, then it should be changed, but I think it really comes down to an issue with multiple inheritance.

For the last term, the direct parent of it is 'confocal microscopy evidence used in manual assertion', which eventually goes up to 'direct assay evidence used in manual assertion' (IDA). Most of the terms do fall under EXP since they are (primarily) all types of 'experimental evidence'. 

This mapping was generated by a SPARQL query with filtering, so any terms that have multiple inheritance end up mapped to the more specific code. We are working on a cleaner way to map terms as per #124... this may help clear up some of the multiple inheritance issues.

**Comment by tonysawfordebi** [comment]
Hi @rctauber 

The other thing that I noticed is this:

ECO:0000320	IKR	Default
ECO:0000320	IMR	Default

IMR is a (deprecated, I believe) synonym for IKR (http://www.geneontology.org/page/ikr-inferred-key-residues).

**Comment by rctauber** [comment]
Thanks for pointing that out @tonysawfordebi. I used the mappings in gaf-eco-mapping.txt so it looks like it exists there as well. I'll bring this up, but this might need to be a tracker issue on it's own.

**Comment by rctauber** [comment]
Hi @cmungall - following up on this issue. Does the gaf-eco-mapping-derived file fulfill this, or does this still need more work?

Thanks!

**Comment by tberardini** [comment]
Question about the ECO terms that are children of ECO_0000011 (Genetic Interaction Evidence):

ECO_0000054 double mutant phenotype evidence
ECO_0000056 epistatic interaction evidence
ECO_0000012 functional complementation evidence
ECO_0000052 suppressor/enhancer interaction evidence
ECO_0000064 functional complementation in heterologous system evidence
ECO_0000038 transient rescue experimental evidence

I expect all of these to map up to IGI in this mapping file:
https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/gaf-eco-mapping-derived.txt

However, there's only this entry for IGI:

ECO:0000316	IGI	Default

ECO:0000316 = Genetic Interaction Evidence Used in Manual Assertion

Should there be child terms under ECO:0000316 that would be the 'used in manual assertion' counterparts of the list I made above?  If not, should all of those terms move to be children of the 'IGI' ECO term instead?

(similar question for IPI ECO:0000353 and its sibling terms that are all under ECO:0000021)

**Comment by rctauber** [comment]
Hi @tberardini -
The classes you mentioned above are raw evidence types, meaning they are not linked to a 'manual assertion'. While they are asserted children of 'genetic interaction evidence', they are not children of 'genetic interaction evidence used in manual assertion' - which is what IGI is mapped to. If you need these terms, I am happy to make the 'manual assertion' children of them so that they can be mapped to IGI.

**Comment by tberardini** [comment]
> If you need these terms, I am happy to make the 'manual assertion' children of them so that they can be mapped to IGI.

Yes, please, for both the 'genetic interaction evidence' and 'physical interaction evidence' children that don't have a 'manual assertion' counterpart.

**Comment by rctauber** [comment]
@tberardini I just added these terms to eco-edit, and they'll show up in the mapping file in the next release (Oct 6) 😃

**Comment by tberardini** [comment]
Thanks very much, @rctauber.

**Comment by rctauber** [comment]
@cmungall - is this issue safe to close?
