### ISSUE TITLE
Mapping up to IMP

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#117]
GO IMP maps to mutant phenotype evidence (or 'mutant phenotype evidence used in manual assertion???').  But many important types of phenotypic evidence that should be covered by IMP, are actually siblings of 'mutant phenotype evidence'.  Perhaps IMP should actually map to the parent term?

![image](https://cloud.githubusercontent.com/assets/112839/20567553/0af700be-b191-11e6-9b39-84cab5d49c84.png)

![image](https://cloud.githubusercontent.com/assets/112839/20567579/230d3128-b191-11e6-93a1-82cd716b52cc.png)

![image](https://cloud.githubusercontent.com/assets/112839/20567622/4ffc7b76-b191-11e6-9492-d5bcb83ea499.png)

CC @cmungall @ukemi @vanaukenk

**Comment by rctauber** [comment]
Hi @dosumis -

Looking over the other classes that fall under 'experimental phenotypic evidence', I'm not sure if it would make sense to map IMP to 'experimental phenotypic evidence used in manual assertion'. While there are a great deal of terms that refer to mutant phenotypes and make sense with IMP, there a few that don't ('voucher specimen evidence' for example).

I spoke with @nsuvarnaiari and we were thinking it would be best to move the terms 'RNAi evidence' and 'genetic transformation evidence' to be under 'mutant phenotype evidence'. In addition, we could create terms like 'RNAi evidence used in manual assertion' so that they correctly fall under IMP, which is mapped to 'mutant phenotype evidence used in manual assertion'. 

Other terms (such as 'biochemical trait analysis evidence', terms relating to mutations, 'anti-sense experiment evidence', etc.) could be moved as well... 

Let me know your thoughts, thanks!

**Comment by dosumis** [comment]
That sounds like a reasonable solution.

**Comment by rctauber** [comment]
Hi again -

We spoke about this issue at our group meeting today and are working on a slightly different solution for GO codes (see #124). Right now, we are going to move some of the apparent 'mutant' terms under 'mutant phenotype evidence' (i.e. the various mutation evidences), but not all of the terms that GO considers IMP. Instead, we will change IMP to map to 'experimental phenotypic evidence used in manual assertion' (which doesn't exist, but I'll create) for now. 

Any children of that (ectopic expression, RNAi, etc.) will map to IMP in the derived mapping file (see #116). I'll take care of this and close this issue.

Thanks!

**Comment by rctauber** [comment]
Reopening as per #125

**Comment by dosumis** [comment]
>  Right now, we are going to move some of the apparent 'mutant' terms under 'mutant phenotype evidence' (i.e. the various mutation evidences), but not all of the terms that GO considers IMP

Can you list the problematic terms?  GO Eds would like to discuss.

Cheers,
David

**Comment by rctauber** [comment]
Just finished discussing the these terms with @nsuvarnaiari ...

First thing first, we want to move 'genetic transformation evidence' under 'mutant phenotype evidence' as originally discussed. That completely makes sense under that parent term, but we want to check in first. These other terms also should be under 'mutant phenotype evidence':
- Mutation terms (point mutation, insertion mutation, deletion mutation, translocation mutation)
- Repeat expansion mutation evidence
- Random mutagenesis evidence
- Splice site mutagenesis evidence
- Splice site mutation evidence
- over expression evidence *
- ectopic expression evidence *
- constitutively active mutant evidence
- dominant-negative mutant evidence
- natural variation mutant evidence
All of these terms will get 'used in manual assertion' children as well so that they will appear under IMP.

* These 2 terms raised some issues, but upon further research we agree that they belong here.

These are the terms that were discussed. A mutant would be applicable in any case where an allele other than the wild-type allele is expressed. In the case of some terms, like the ones listed below, the wild-type allele could still be present, and the gene is not changed, only the expression.
- anti-sense experiment evidence (blocking/silencing)
- morpholino experiment evidence (blocking/silencing)
- RNAi evidence (blocking/inhibition)

If there are any other terms you think should fall under 'mutant phenotype evidence', please just let me know.

**Comment by dosumis** [comment]
I'd be happy for the anti-sense, morpholino and RNAi evidence to be under 'mutant phenotype evidence'.

**Comment by dosumis** [comment]
Any progress on this? Seems that genetic transformation evidence is still not under mutant phenotype evidence.  Do you still need feedback from me?

Many thanks,
David

**Comment by rctauber** [comment]
Hi again @dosumis -

Sorry for the delay. We are going to move 'genetic transformation evidence' under 'mutant phenotype evidence' today. We are also working on rewriting the definitions and moving 'anti-sense experiment evidence', 'morpholino experiment evidence', and 'RNAi evidence'. This should be completed later today.

Thank you so much for your patience, and I apologize again that this has been open so long.

**Comment by rctauber** [comment]
Hi @dosumis - I would like to follow up on this issue and see if it has been resolved, or if we still need to do more work on this?

Thanks!
