### ISSUE TITLE
plasmid maintenance assay evidence, under ECO:0000006

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#12]
```
1. succinct term name: plasmid maintenance assay evidence

2. definition: Evidence from an assay in which a mitotically stable plasmid (or 
minichromosome) is introduced into cells, the cells are grown without selection 
for several generations, and the proportion of cells that retain the plasmid is 
then determined (by comparing colony numbers on selective versus non-selective 
media) and the loss per generation calculated.

3. n/a

4. Suggested parent term: I'm confident that it belongs somewhere under 
ECO:0000006 'experimental evidence', but beyond that I'm not sure where it 
might fit more specifically.

5. Reference for the definition: PMID:6323245

Additional information: synonym: "minichromosome maintenance assay evidence" 
EXACT [PMID:6323245]


Transferred and updated from request on the old SourceForge tracker 
(https://sourceforge.net/tracker/?func=detail&atid=1127740&aid= 
3500434&group_id=36855).

Thanks,
Midori

```

Original issue reported on code.google.com by `midori.h...@gmail.com` on 10 Aug 2012 at 10:20

**Comment by jimhu-tamu** [comment]
Reopen. This should not be restricted to mitotic cells because the class of assay evidence is relevant to bacteria. For example:

https://www.ncbi.nlm.nih.gov/pubmed/4576229

It might be appropriate (or not) to have parent-child terms to distinguish between eukaryotic and bacterial/archael systems but I'm not sure. I suspect that additional intermediate parents might also be useful in the long run.

**Comment by rctauber** [comment]
We can reopen this issue to discuss.

**Comment by mgiglio99** [comment]
Hi @jimhu-tamu 
We've come up with two options for how to handle this:
1. We could just remove the phrase "mitotically stable" from the definition. This will make the term more broad and focus the evidence on the plasmid maintenance part.
2. We could rephrase so that it works for any kind of cell division. For example: change "mitotically stable" to "...in which a plasmid that is capable of being replicated during cell division is introduced..."

We'd rather not make euk/prok parent terms at this point. Just doesn't seem to be a need and the basic assay is the same in both.

Do one of these options look good to you?

**Comment by mgiglio99** [comment]
Hi @jimhu-tamu 
Just checking if you are ok with one of the above options.
Michelle

**Comment by mgiglio99** [comment]
Hi @jimhu-tamu ,
Please let us know if one of the above options will work.
Thanks 
Michelle

**Comment by mgiglio99** [comment]
We've decided to go with option 2.
Proposed new def:
"A type of experimental evidence in which a plasmid that is capable of being replicated during cell division is introduced into cells, cells are grown without selection for several generations, and retention of the plasmid is determined."
@jimhu-tamu Let us know if you have any objections. If we don't hear in a week, we will push this change.

**Comment by jimhu-tamu** [comment]
sorry for not replying to the earlier ping. My only question is whether "during cell division" is too specific and users will interpret that as replication happening during M phase vs S phase of a eukaryotic cell cycle, or in sync with chromosomal replication. 

Why not drop "during cell division" and let 'capable of being replicated" be sufficient?

**Comment by mgiglio99** [comment]
Sounds good to me.
Final new def:
"A type of experimental evidence in which a plasmid that is capable of being replicated is introduced into cells, cells are grown without selection for several generations, and retention of the plasmid is determined."

**Comment by jbmunro** [comment]
The new definition has been added and pushed.

Closing this ticket.

James
