### ISSUE TITLE
Mapping of ECO:0005802

### ISSUE THREAD

**Issue by hdrabkin** [evidenceontology/evidenceontology#127]
cell transfection experiment evidence used in manual assertion (ECO:0005802) maps to EXP; why not to IDA?

**Comment by rctauber** [comment]
The parent class ('cell transfection experiment evidence' ECO:00056006) is a child of 'experimental evidence' ('experimental evidence used in manual assertion' = EXP), rather than a child of 'direct assay evidence'. So, actually, it's a sibling of 'direct assay evidence'... I'm not exactly sure why it isn't a child of 'direct assay evidence' (which would make ECO:0005802 map to IDA). Or 'experimental genomic evidence'... also IDA.

CC @nsuvarnaiari - looks like you created this term so what are your thoughts?

**Comment by nsuvarnaiari** [comment]
@pgaudet requested the term in the ticket #87. 
Pascale, pls let us know your thoughts.

**Comment by hdrabkin** [comment]
ah! wait; I see that it doesn't say .. used in manual assertion. 
So, actually I'd like a term cell transfection experiment evidence used in manual assertion, child of IDA

Should I close this ticket and make a new one; sorry

**Comment by mchibucos** [comment]
Hi @hdrabkin. Feel free to create a new issue if it's not inconvenient. I'll close this one.

**Comment by pgaudet** [comment]
Hello, 

Is this resolved ? The issue for us was not manual versus automated assertion; it was that a transfection is not a direct measure of a protein activity, so it cannot be a child of IDA. Harold, is this OK with you ? 

Thanks, Pascale
