### ISSUE TITLE
New parent terms for biological systems reconstruction children

### ISSUE THREAD

**Issue by bmeldal** [evidenceontology/evidenceontology#145]
We added a bunch of terms to capture the evidence for protein complexes (and potentially pathways) but not all are mapped to old GO evidence codes. Our Complex Portal annotations without mapping to GO codes are currently stuck in the pipeline. I'm requesting the following new relationships:

ECO:0005610 - biological system reconstruction evidence based on homology evidence used in manual assertion
is_a ECO:0000252 - similarity evidence used in manual assertion

ECO:0005547 - biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion
is_a ECO:0000304 - traceable author statement used in manual assertion

ECO:0005543 - biological system reconstruction evidence by experimental evidence from mixed species used in manual assertion
is_a ECO:0000250 - sequence similarity evidence used in manual assertion

ECO:0005542 - biological system reconstruction evidence by experimental evidence from single species used in manual assertion
is_a ECO:0000353? - physical interaction evidence used in manual assertion

Originally, we didn't link them up to existing codes as annotating to complexes is different to annotating to single gene products. But it looks like we can't get our annotations out without this hack :(

ECO:0005542 is the tricky one: we use it when no single experiment contains evidence for all complex members together but there are 2 or 3 expts, when taken together, that provide evidence for the whole complex. Evidence comes from experimental interaction evidence but in multiple experiments (but all have to be done in the same species)

@sandraorchard have I captured that correctly?

**Comment by rctauber** [comment]
Hi @bmeldal - sorry it's taken so long to respond. Based on a meeting with @jbmunro and @nsuvarnaiari, here's our thoughts.

We are currently in the process of adding logic to ECO by incorporating OBI and mapping ECO evidence classes to various OBI classes. In this project, we are trying to remove dual asserted parentage and use the logic to infer secondary parentage. At this point in time, we've only mapped terms in the 'experimental evidence' node. The best solution to this problem would probably be to try and find the logical mappings for these terms so that these second parents can be inferred, rather than asserted.

That said, this is a work in progress and is not ready for release yet. I'm not sure of the time frame right now. If these terms are causing issues in your pipeline, we can add the second parent for now, and then remove it once the OBI logic has been added in. It is preferable to avoid dual parentage, but we want to make sure everything is working smoothly for you!

Now onto the specifics...

**'biological system reconstruction evidence based on homology evidence'**
Makes sense to also be 'similarity evidence'

**'biological system reconstruction evidence based on inference from background scientific knowledge'**
This one is a little problematic. It is not a 'traceable author statement', though it may be a 'non-traceable author statement' (as they are making a statement without a citation, just based off background knowledge). Ultimately, it is an 'inference from background scientific knowledge', but that does not have an equivalent GO code so we are stuck with the same problem.

**'biological system reconstruction evidence by experimental evidence from mixed species'**
This looks good as 'sequence similarity evidence'

**'biological system reconstruction evidence by experimental evidence from single species'**
This is actually a type of combinatorial evidence. It cannot logically be a child of 'physical interaction evidence' because that only captures ONE experiment. Again, we have the problem that 'combinatorial evidence' does not have an equivalent GO code...

I'm wondering if there are any GO developers that we could reach out to and review these terms to try and find the best GO code match?

**Comment by bmeldal** [comment]
Hi Rebecca,

I completely forgot about this ticket! We had another meeting with the GOA developers and it turned out that we probably won't need links to existing GO evidence codes as the GPAD format, which we are using, allows all ECO codes. (There was a little confusion about where our annotations got stuck and what we wanted to achieve). We are still trying to tease out exactly how best to integrate complex annotation into GO.

So, 
- I'm happy for the parentages to be inferred by logical mapping.
- Only implement those inferences that don't have to be 'forced', i.e.

>'biological system reconstruction evidence based on homology evidence'
>Makes sense to also be 'similarity evidence'

and

> 'biological system reconstruction evidence by experimental evidence from mixed species'
> This looks good as 'sequence similarity evidence'

Birgit

**Comment by rctauber** [comment]
Good to hear @bmeldal !

Is it safe to close this ticket, then? This inferences will probably be implemented as we progress through the mapping project, but if you need them sooner please let me know...

**Comment by bmeldal** [comment]
Ok, I'll close the ticket and if we need anything after all I'll re-open.
