### ISSUE TITLE
FLIPR assay

### ISSUE THREAD

**Issue by FJungo** [evidenceontology/evidenceontology#153]
Hi,
I would like to tag the experiment type "calcium imaging measured with fluorescence (such as FLIPR assay)", but I hesitate between two terms:fluorescence evidence; ECO:0001115 and imaging assay evidence; ECO:0000324. Could you give me your opinion ?
Many thanks,
Florence

**Comment by rctauber** [comment]
Hi @FJungo - would it be useful to have a 'calcium imaging evidence' term? Or, more specifically, 'FLIPR assay evidence'?

**Comment by FJungo** [comment]
Hi @rctauber
Something like   - fluorescent imaging evidence
(as indicated in table 2 of PMID:25979003, and see also methods of PMID:17093448, for example)
would be excellent.  And it can be child of both
-fluorescence evidence; ECO:0001115  and
-imaging assay evidence; ECO:0000324

**Comment by rctauber** [comment]
Hi again @FJungo - I'd like to discuss this with the rest of the ECO team, as it seems a term like that would require some restructuring of existing ECO classes. For example, identifying existing classes that would belong as subclasses of 'fluorescent imaging evidence'.

**Comment by rctauber** [comment]
Hi @FJungo - I'd like to follow up on your request.

We are trying to focus on building ECO around what the evidence is *about*, not just techniques used in various assays. For this reason, 'fluorescent imaging evidence' is a bit too general, because it doesn't talk about what's being measured - it's just a technique to measure something. We are spending some time restructuring parts of ECO to fit this idea.

Would you still like to add the term FLIPR assay evidence? More generally, I would suggest something like 'membrane potential assay evidence' rather than 'fluorescent imaging evidence'. Perhaps you could provide some more context on what is being annotated? Thank you!

**Comment by FJungo** [comment]
Hi @rctauber 
For the moment, I will use the term imaging assay evidence; ECO_0000324, and will revisit it in a few months after the restructuring you mention.
Thanks

**Comment by rctauber** [comment]
Great - I'll mark this as closed for now. Feel free to reopen when ready, or just create a new issue with your new term request. Thanks!
