### ISSUE TITLE
microarray evidence

### ISSUE THREAD

**Issue by ivanerill** [evidenceontology/evidenceontology#155]
ECO now contains many evidence terms for "microarray evidence". On quick inspection, I can see:
- ECO:0005524 - DNA microarray evidence (a molecule detection assay evidence)
- ECO:0000104 - microarray RNA expression level evidence (an expression pattern evidence)
- ECO:0000058 - expression microarray evidence (an expression pattern evidence), ECO:0000104 parent
- ECO:0000093 - oligonucleotide microarray evidence (an expression pattern evidence), which appears to be devoted to protein-DNA binding arrays
- ECO:0000097 - cDNA microarray evidence (an expression pattern evidence)
- ECO:0000101 - Affymetrix array experiment evidence (an expression pattern evidence)
- ECO:0000105 - Nimblegen array evidence
and the respective cross-products with "manual assertion". 

I fail to see why this plurality is necessary. I can understand that Affymetrix and Nimblegen are specialized microarray types, and that protein-DNA binding is a different type of evidence from conventional DNA arrays. I don't see, however, how ECO:0005524, ECO:0000104 or ECO:0000097 should be distinct terms. As far as I know, all arrays are based on cDNA strands isolated on a surface, and exploit RNA hybridization (directly or after RT-PCR) on those probes for detection, with the canonical application being measurement of RNA expression levels.

**Comment by rctauber** [comment]
Thank you for calling our attention to this @ivanerill - there are definitely issues in this node that need to be resolved. We will be working on this as soon as everyone is back from the holidays.

**Comment by ivanerill** [comment]
Perfect, let me know how I can contribute. Happy holidays!

**Comment by rctauber** [comment]
Hi @ivanerill -
I wanted to give you an update on what we've been working on in regards to this issue. Please let me know if you have any suggestions!

We would like to deprecate the class 'array experiment evidence' and move all the children to more appropriate locations. We feel that the classes should be categorized based on what is being analyzed, rather than the technique or technology. This means most of them will be relocated to 'transcript expression evidence'. 

As for the microarray evidence types you mentioned above... the naming of microarrays is a bit foggy. Rather than choosing one label that may or may not confuse users, we are proposing to label the microarray classes based on what is being hybridized to what is immobilized on a surface. For example, 'cDNA to DNA expression microarray' involves RNA being reverse transcribed to cDNA, then hybridized to DNA. Any relevant terms will be merged together.

- transcript expression evidence
  - expression microarray evidence
    - cDNA to DNA expression microarray evidence (cDNA microarray evidence, RNA microarray evidence, and DNA microarray evidence merged)
        - Nimblegen array evidence
    - DNA to cDNA expression microarray evidence (previously microarray RNA expression level evidence, which is RNA expression microarray - a "reverse format" array)
    - cRNA to DNA expression microarray evidence (previously genomic microarray evidence)
        - Affymetrix GeneChip evidence

Oligonucleotide arrays can actually be used for DNA, RNA, or protein binding. 'protein-binding microarray evidence' should be moved to 'protein binding evidence', and then 'oligonucleotide microarray evidence' could be included as a related synonym for both 'expression microarray evidence' and 'protein-binding microarray evidence'.

For the other array experiment evidence children... 'CpG island microarray evidence' will be merged into 'differential methylation hybridization evidence' and 'tissue microarray evidence' will be moved to be a child of 'cytochemistry evidence'.

Sorry this response is so long, and hopefully it makes sense. I'm making a draft of the changes in Protege now, so if you'd like to see that file, just let me know.

**Comment by rctauber** [comment]
The changes have been pushed to `eco-edit.owl` and will be live with our March release. Please let me know if you have any thoughts, otherwise we will close this issue. Thanks! 🙂

**Comment by ivanerill** [comment]
The changes look good to me. Thanks!
