### ISSUE TITLE
New ECO term : Radioligand binding assays recording evidence

### ISSUE THREAD

**Issue by FJungo** [evidenceontology/evidenceontology#157]
Hi,
Here is a suggestion for a new ECO term related to a technique to prove protein binding.

Protein binding evidence; ECO_0000024
  Radioligand binding assays recording evidence; ECO_xxx 

Regards

**Comment by rctauber** [comment]
Hi @FJungo! Thank you for your request. Could you provide a source for a definition for this term, such as a PMID or other published journal article?

**Comment by FJungo** [comment]
Hi @rctauber ! 
Here are two papers where the protein binding is proved thanks to "radioligand binding assays": PMID:11707459 and PMID:12488533
As a definition, I suggest:
A type of affinity evidence which involves measurement of competitive binding between a protein or a protein complex and a radioligand.
Tell me if you need other papers.
Thanks

**Comment by rctauber** [comment]
Thank you! I agree that it is a type of `protein binding evidence`.

It looks like there are multiple types of radioligand binding assays, one of which is the competitive binding assay. My proposal for a definition for radioligand binding assay evidence is as follows, as it appears there are different subtypes of radioligand binding assays:
> A type of protein binding evidence in which radioactive ligands are used to measure receptor-ligand interactions, such as in determining selectivity for a particular ligand.

That said, I would include `competitive binding assay evidence` as a narrow synonym.

I also found this resource for the definition: [PMID:27471749](https://www.ncbi.nlm.nih.gov/pubmed/27471749). I only mention this because it is more recent (2015) than the papers you provided (2002, 2003), but I think it gets the same idea across.

Alternative labels (synonyms):
* [radiometric ligand-binding assay](http://www.perkinelmer.com/lab-products-and-services/application-support-knowledgebase/radiometric/radiometric-ligand-binding-assays.html)
* [radioactive ligand binding assay](https://en.wikipedia.org/wiki/Ligand_binding_assay#Radioactive_Ligand_Binding_Assays)

**Comment by FJungo** [comment]
Many thanks Rebecca
I like your definition and completely agree with the synonym you propose.
Just one additional question, but more practical: Do you have an idea when the new term will be available in OLS ?
Best

**Comment by rctauber** [comment]
I'm going to put it into eco-edit today. We do releases on the 1st Friday of the month, so the next release will be January 5th. That said, if it's urgently needed, I can do an unscheduled release.

**Comment by FJungo** [comment]
Thanks. No, it's not urgent, it was just to have an idea. Thanks!

**Comment by rctauber** [comment]
Great, I'm putting in ECO:0007008 (radioligand binding assay evidence) and ECO:0007009 (radioligand binding assay evidence used in manual assertion). I'll close this issue with that commit, but if you need anything else please just reopen!
