### ISSUE TITLE
Review of 'reporter gene assay evidence' branch

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#173]
Currently reviewing 'reporter gene assay evidence' branch and creating this ticket to document discussions and notes.

[reporter gene assay evidence.docx](https://github.com/evidenceontology/evidenceontology/files/2315501/reporter.gene.assay.evidence.docx)
[reporter gene assay evidence2.docx](https://github.com/evidenceontology/evidenceontology/files/2315502/reporter.gene.assay.evidence2.docx)

James

**Comment by ivanerill** [comment]
The proposed move of `reporter gene assay evidence` terms from `experimental phenotypic evidence` to `expression pattern evidence` seems a priori adequate, but probably requires some further discussion.

A possible caveat might be the usage note on `expression pattern evidence`, which states 

>"Use this evidence type when the annotation is inferred from the _timing or location_ of expression of a gene."

 and reporter gene assays are frequently used in contexts (e.g. regulatory gene knockout vs. wild-type comparison) where neither the timing or location are necessarily determining factors for the inference.

More generally, an objection to such a move can be made on the basis that several of the children within `reporter gene assay evidence` seem, in principle, to be a better fit for `experimental phenotypic evidence`. This is because most terms under `expression pattern evidence` involve the use of molecular techniques to read out gene expression (e.g. `ribosome profiling evidence` or `expression microarray evidence`), whereas methods such as `beta-galactosidase reporter gene assay evidence` or `Cya fusion reporter assay evidence` are actually measuring a phenotype (manifested in cell culture or even in another organism) to assess (and/or quantify) gene expression.

**Comment by pgaudet** [comment]
Hi @ivanerill 
I think the issue has to do with 'pattern', which fits the comment regarding timing and localization. Perhaps reporter gene assay should not be under IEP ? 

Pascale

**Comment by ivanerill** [comment]
Hi @pgaudet ,

Precisely. The tricky issue is that oftentimes it could be argued that `reporter gene assay evidence` is used to look at _patterns_ of expression (e.g. when performing a reporter assay on an inducible promoter, or when analyzing the expression of gene+reporter construct in different settings), but this is typically done on a single gene at a time. I always understood the original GO IEP code to encompass mostly evidence that made use of expression correlation with other genes (also assessed during the experiment and known to participate in a biological process) to make inferences about a gene's participation in that BP. This would not fit the above `reporter gene assay evidence` scenarios. However, one can also frame `reporter gene assay evidence` as inference based on previously available knowledge. For instance, if I want to test if a gene is induced by heat shock and I know that genes induced by heat shock in that organism go up more than 2-fold when exposed to a +10 ºC temperature change, I can set up a reporter assay and test whether a gene of interest follows the same _pattern_.

**Comment by mgiglio99** [comment]
This node was addressed (long ago but this issue wasn't closed) - the move of 'reporter gene assay evidence' was made and children of 'reporter gene assay evidence' were sorted out and rehomed as needed.
