### ISSUE TITLE
NTR: 'small molecule detection assay evidence'

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#180]
Hello @ivanerill and @ehobbs2,

In recent joint CollecTF and ECO discussions it was suggested that the term 'small molecule detection assay evidence' be added as a child of 'molecule detection assay evidence'.  

NTR label: 'small molecule detection assay evidence'

NTR proposed definition: A type of molecule detection assay evidence resulting from the detection and quantification of a small molecule (a low molecular weight (< 900 daltons) organic compound).

xrefs: PMID:29874046, PMID:27379229

Suggestions are welcome.

Thanks.

James

**Comment by mgiglio99** [comment]
Looking good. I'm a bit worried about putting an actual mol wt number in - maybe add the qualifier "typically" or "generally". Also some examples might be nice - something like "...such as lipids, sugars, animo acids, drugs, etc."
Should we make synonyms using the term "metabolite" instead of small molecule?

**Comment by jbmunro** [comment]
Totally on board with adding "...(typically <900 daltons)..." to the def.

Would the examples you suggest be part of the definition or added in comments?

I can certainly add 'metabolite detection assay evidence' as a synonym - narrow or exact?

James

**Comment by mgiglio99** [comment]
I think the examples would be good in the definition. 
Not sure on narrow or exact. Maybe narrow.

**Comment by jbmunro** [comment]
NTR created.  Closing this ticket.
James
