### ISSUE TITLE
NTR: infection assay evidence

### ISSUE THREAD

**Issue by ivanerill** [evidenceontology/evidenceontology#184]
Many papers in microbiology (e.g. PMID:19236707, PMID:25170934) make use of animal/plant models to assess the virulence or pathogenic ability of microorganisms (e.g. viruses, bacteria). The animal/plant model is exposed to the pathogen and some type of phenotypic outcome is measured in the host (e.g. mortality, immune response...).

The proposed definition would be as follows:

> Infection assay evidence is a type of experimental phenotypic evidence in which the virulence or infection capacity of a pathogen is determined by assessing phenotypic changes in the host.

Most likely parent term would be: `ECO:0000059 - experimental phenotypic evidence`, but it must be noted that `ECO:0000179 - animal model system study evidence` might be a better parent term for the term here proposed when applied to animal hosts. 

In the case that specific terms were to be derived from "infection assay evidence" based on the type of host used for the experiment (e.g. "plant infection assay evidence), corresponding terms equivalent to `ECO:0000179` should be derived (e.g. "plant model system study evidence", "cell culture model system study evidence") to act as parents.

**Comment by jbmunro** [comment]
Hi @ivanerill,

Thank you for the NTR.  We discussed this at our last ECO meeting and I will update the ticket shortly with some ideas.

James

**Comment by jbmunro** [comment]
Hi @ivanerill,

Apologies for the delay.  Moving forward with new terms as noted below.  I will have this pushed to GitHub shortly.  I am closing the ticket but please feel free to re-open it if need be.

James

**NTR: host colonization assay evidence**
**child of:** experimental evidence 
**def:** A type of v experimental evidence in which the colonization or adhesion capacity is measured.
**comment:** Has to do with the ability of the bacterium or virus to bind to a host.
**exact syn.:** adhesion assay evidence

**NTR: host colonization assay evidence used in automatic assertion**
**def:** A type of host colonization assay evidence that is used in an automatic assertion.

**NTR: host colonization assay evidence used in manual assertion**
**def:** A type of host colonization assay evidence that is used in a manual assertion.

**NTR: infection assay evidence**
**child of:** host colonization assay evidence 
**def:** A type of host colonization assay evidence in which the infection capacity is measured by assessing changes in the host.
**comment:** Has to do with the outcome of a bacterial or viral / host interaction, be it a measure of cell death, cytotoxicity, invasion, etc.

**NTR: infection assay evidence used in automatic assertion**
def: A type of infection assay evidence that is used in an automatic assertion.

**NTR: infection assay evidence used in manual assertion**
def: A type of infection assay evidence that is used in a manual assertion.

**Comment by ivanerill** [comment]
Just wondering if "NTR: host colonization assay evidence" should be a child
of ECO:0000059 instead?

**Comment by mgiglio99** [comment]
I've been avoiding putting things under ECO:0000059 'experimental phenotypic evidence' because I don't think there is a clear distinction between what belongs under 'direct assay ' and what goes under 'experimental phenotype'. I need to think about it some more -but I kind of feel that most things are phenotypic observations so I'm not sure it's useful to have a separate grouping term. But that is still on our 'to do' list to review in depth.

**Comment by ivanerill** [comment]
The way I see it this harks back to the question of what evidence is, leading you to adopt an intentional stance. If you "use" the phenotype _to make your assertion_ (i.e. you just observe it directly, you measure some aspect of it (e.g. concentration of a protein), etc.) then it should be some kind of 'phenotypic evidence'.

For instance, if you measure growth of a cell population and a mutant population to determine some role of the knocked out protein in certain conditions, then this is obviously 'mutant phenotype' evidence. 

It is hard to conceive of a case in which the phenotype is "used" in the above sense in an IDA-like context.  You can only "use" the phenotype if you perform an in vivo experiment (although there might be some final in vitro stages involved in reading out the phenotype). Both the references cited in my original NTR use mutants, so should probably inherit from [ECO:0000015](https://www.ebi.ac.uk/QuickGO/term/ECO:0000015) or one of its offspring (or may already be covered by one of those).

I've been trying to come up with an IDA-like instance of experimental evidence where the phenotype is used in the sense above, but I have not been able to. If you guys can't either I would probably suggest obsoleting [ECO:0000059](https://www.ebi.ac.uk/QuickGO/term/ECO:0000059).

**Comment by mgiglio99** [comment]
Hi @ivanerill 
In fact, I've been wanting to obsolete ECO:0000059 'experimental phenotypic evidence' - but didn't want to state that until we had time to review things more.
We can't put 'infection assay evidence' under ECO:0000015 'mutant phenotype evidence' since it will not always be mutants that are involved. 
Perhaps you can solve this by doing two annotations, one to 'infection assay evidence' and one to 'mutant phenotype evidence'.
We're happy to get on a call and chat on this if you'd like.

**Comment by jbmunro** [comment]
Re-opening issue as there was further discussion.

 @ivanerill - let us know if discussing this over the phone / online meeting would be helpful.

James

**Comment by jbmunro** [comment]
**Summary:**
'host colonization assay evidence' and its child term 'infection assay evidence' were created under 'experimental evidence' and the ticket was closed.

Ivan questioned the 'experimental evidence' parentage and suggested 'experimental phenotypic evidence'.   As noted, there is hesitation on the part of ECO to do this as this branch is under review with the probable outcome of finding new parents for the children and obsoleting the term (GitHub #174).  Additionally, it was noted that the parent 'mutant phenotype evidence' is inappropriate since it will not always be mutants that are involved.

Given that there has been no further discussion for over 3 weeks, I am closing this ticket with the understanding that it can be opened again if need be.
