### ISSUE TITLE
NTR: Annexin-V and PI staining evidence

### ISSUE THREAD

**Issue by MABeebe** [evidenceontology/evidenceontology#218]
NTR: Annexin-V and PI staining evidence
Definition: A type of apoptotic assay evidence resulting from the addition and subsequent binding of Annexin V to phosphatidylserine along with the presence of propidium iodide in the cytosol of cells to detect if they are viable, apoptotic, or necrotic.
Parent: ECO:0005034
PMID:25461800
Will also need “used in manual/automatic assertion” terms
@jimhu-tamu
@sandyl27

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

I will get going on this early next week.

James

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

I will bring the following suggestions up at the next ECO meeting.

James

**NTR: annexin V and propidium iodide staining evidence**
**child of:** apoptotic assay evidence
**def:**  A type of apoptotic assay evidence resulting from the addition and subsequent binding of annexin V and propidium iodide to cells in order to detect if they are viable, apoptotic, or necrotic.
**comment:** Annexin V binds to phosphatidylserines, which normally occur only in the inner, cytoplasm-facing leaflet of a cell’s membrane, but become “flipped” to the outer leaflet during the early stages of apoptosis. Propidium iodide will bind to the DNA of cells once the membrane is ruptured, which is indicative of necrosis and late apoptosis.
**dbxref:** PMID:25461800
**dbxref:** PMID:21540825
**exact synonym:** annexin V and PI staining evidence
 
**NTR: annexin V and propidium iodide staining evidence used in automatic assertion**
**def:** A type of annexin V and propidium iodide staining evidence that is used in an automatic assertion.

**NTR: annexin V and propidium iodide staining evidence used in manual assertion**
**def:** A type of annexin V and propidium iodide staining evidence that is used in a manual assertion.

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

Following up to see where things stand with the above NTR and suggestions.

James

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

Following up again to see where things stand with the above NTR and suggestions.

James

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

Can I assume that you are OK with using the two established terms?  

James

**Comment by sandyl27** [comment]
Thats fine!

**Comment by jbmunro** [comment]
Hi @sandyl27,

Terrific!  Thanks!  Closing the ticket.

James
