### ISSUE TITLE
ECO:0000096 - ECO:0000023 Relationship

### ISSUE THREAD

**Issue by stephengoralski** [evidenceontology/evidenceontology#224]
Currently, ECO:0000096: Electrophoretic Mobility Shift Assay Evidence is a direct child term of ECO: 0000002: Direct Assay Evidence. The UMBC ECO team, however, has noticed that EMSA would be more accurately described as a child term of ECO:0000023: Affinity Evidence.

**Comment by stephengoralski** [comment]
@ivanerill

**Comment by stephengoralski** [comment]
Sorry, I am unfamiliar with GitHub. Ivan Erill also asked to be added to this conversation, but I'm not totally sure how to do that.

**Comment by jbmunro** [comment]
Hi @stephengoralski and @ivanerill,

Adding Ivan.  Stephen - simply add "@" and then the user name.

Thanks for suggested relationship.  I will look into it and bring it up at the next meeting.

James

**Comment by jbmunro** [comment]
Hi @stephengoralski and @ivanerill,

The following resulted from our discussion of the above 

1.	Michelle noted that moving electrophoretic mobility shift assay evidence (ECO:0000096) to affinity evidence (ECO:0000023) would make it a grandchild of physical interaction evidence (ECO:0000021).  Michelle was worried that would make it a child of GO IPI.  I checked gaf-eco-mapping-derived.txt and gaf-eco-mapping.txt and it doesn't seem to be the case as physical interaction evidence (ECO:0000021) doesn't seem to be listed in either file. However, I am waiting for confirmation.
2.	Shouldn’t it actually be a child of ‘nucleic acid binding evidence’?  https://doi.org/10.1038/nmeth0705-557 notes that it is a method for studying the DNA-binding properties of a protein and can be used to deduce the binding parameters and relative affinities of a protein for one or more DNA sites or for comparing the affinities of different proteins for the same sites. Similarly, PMID:17703195 notes the use of this method to detect protein complexes with nucleic acids.  
3.	Definition seems inconsistent - macromolecules, compounds, and proteins vs. solutions of protein and nucleic acid are combined.  Given PMID:17703195 and the above citation, shouldn't this be limited to proteins and nucleic acids?

**suggested new parent:** nucleic acid binding evidence (ECO:0000136)

**suggested new def.:** A type of nucleic acid binding evidence based on an electrophoretic mobility shift of macromolecules, where proteins and nucleic acids are combined and the resulting mixtures are electrophoresed under native conditions through polyacrylamide or agarose gel to detect protein-nucleic acid interactions/complexes.

**Comment by jbmunro** [comment]
Hi @stephengoralski and @ivanerill,

A quick update to point #1 above:

Currently electrophoretic mobility shift assay evidence is GO:IDA.  Moving it to affinity evidence or nucleic acid binding evidence will make it GO:IPI

James

**Comment by stephengoralski** [comment]
Hi @jbmunro , 

In regards to issue #1, I think that EMSA still works under IPI. In an EMSA, you are inferring DNA binding ability through the interaction of DNA with protein. To me, that would justify the change from one to the other. 

As far as issue #2 goes, I am okay with a nucleic acid binding parent instead of affinity. Nucleic acid binding is a child of affinity, so maybe putting EMSA there would provide better clarification. 

I do like the new definition more, as I am fairly certain that only DNA and protein are used in EMSAs. 

Steve

**Comment by ivanerill** [comment]
Hi @jbmunro, @mgiglio99,

> Michelle noted that moving electrophoretic mobility shift assay evidence (ECO:0000096) to affinity evidence (ECO:0000023) would make it a grandchild of physical interaction evidence (ECO:0000021). Michelle was worried that would make it a child of GO IPI. I checked gaf-eco-mapping-derived.txt and gaf-eco-mapping.txt and it doesn't seem to be the case as physical interaction evidence (ECO:0000021) doesn't seem to be listed in either file. However, I am waiting for confirmation.

Correct. Our overall point was that if DNAse footprinting [ECO:0001810](https://www.ebi.ac.uk/QuickGO/term/ECO:0001810) is IPI, so should EMSA. In both cases, binding between a protein and a "known" DNA fragment is established. In the former by cleavage protection and sequencing, in the latter by differential migration in a gel with competing unspecific DNA.
Whether any of the two captures the spirit of the [IPI code](http://wiki.geneontology.org/index.php/Inferred_from_Physical_Interaction_(IPI)) (to which I assume [ECO:0000021](https://www.ebi.ac.uk/QuickGO/term/ECO:0000021) maps), is a different matter.

According to GO, "IPI can be thought of as a type of IDA, where the actual binding partner or target can be specified, using a unique accession or identifier in the With (or) From column (Column 8 in the GAF)". The DNA fragments in DNAse footprinting [ECO:0001810](https://www.ebi.ac.uk/QuickGO/term/ECO:0001810) and EMSA [ECO:0001807](https://www.ebi.ac.uk/QuickGO/term/ECO:0001807) are "known" in the sense that the experimenter is aware of their sequence and/or context, but they typically will not have a unique accession/identifier in any database unless they have been annotated in [CollecTF](http://www.collectf.org/browse/home/), [Prodoric](http://www.prodoric.de) or [RegulonDB](http://regulondb.ccg.unam.mx/).

> Shouldn’t it actually be a child of ‘nucleic acid binding evidence’? https://doi.org/10.1038/nmeth0705-557 notes that it is a method for studying the DNA-binding properties of a protein and can be used to deduce the binding parameters and relative affinities of a protein for one or more DNA sites or for comparing the affinities of different proteins for the same sites. Similarly, PMID:17703195 notes the use of this method to detect protein complexes with nucleic acids.

That is its most frequent use, yes, but it theoretically can be used to identify other types of interaction/binding. See, for instance, [PMID:15064455](https://www.ncbi.nlm.nih.gov/pubmed/15064455) for protein-protein interactions. We chose the root term to avoid committing to nucleic acids.

> Definition seems inconsistent - macromolecules, compounds, and proteins vs. solutions of protein and nucleic acid are combined. Given PMID:17703195 and the above citation, shouldn't this be limited to proteins and nucleic acids?

Depending on which way we go, the definition certainly should be revised to either make the term generic or make it protein-DNA specific.

**Comment by jbmunro** [comment]
Adding a couple of notes from our discussion last week.

1) This node is "complicated" to say the least and needs revision, which I am starting.
2) We need to address the issue of moving electrophoretic mobility shift assay evidence form GO:IDA to GO:IPI - as this could very well impact those that have used this term for annotation.

**Comment by ivanerill** [comment]
>We need to address the issue of moving electrophoretic mobility shift assay evidence from GO:IDA to GO:IPI - as this could very well impact those that have used this term for annotation.

The issue here is that in its most common setting [EMSA](https://www.ebi.ac.uk/QuickGO/term/ECO:0000096) won't meet the GO evidence code requirement that "_the actual binding partner or target can be specified, using a unique accession or identifier in the With (or) From column_". This applies also to several other methods currently under IPI (e.g. [ECO:0001810](https://www.ebi.ac.uk/QuickGO/term/ECO:0001810)).

Yet, EMSA can be applied to detect protein-protein interactions (see [PMID:15064455](https://www.ncbi.nlm.nih.gov/pubmed/15064455) referenced above), so in that case it would be a proper IPI experiment. 

That paper has been cited 18 times, so one could very reasonably argue that EMSA is primarily used for protein-DNA interactions where the identity of the DNA is not known in the sense of IPI (unique identifier), so I would advocate for leaving EMSA as IDA. I would, however, move [ECO:0000136](https://www.ebi.ac.uk/QuickGO/term/ECO:0000136) and its offspring from IPI to IDA for the reasons stated above, and make EMSA a daughter of ECO:0000136 (nucleic acid binding evidence) within IDA. In the rare cases where the binding partner has a unique identifier, curators are free to use the WITH column even though the terms be formally IDA.

**Comment by jbmunro** [comment]
**A quick summary:**
1) The suggestion to move 'electrophoretic mobility shift assay evidence' from 'direct assay evidence' to 'affinity evidence' is valid and will be taken up as soon as point 2 is addressed.
2) We first need to reach out to users of ECO (GO and MODs) who might be impacted by moving 'electrophoretic mobility shift assay evidence' from GO:IDA to GO:IPI.
3) James' suggested new definition (above) needs to be re-worked as Ivan pointed out that it can be nucleic acid/protein and protein/protein.  Rather than create two specific terms, a generic definition, applicable to both cases, will be kept.  (If in the future more granular terms are requested, they can be added.) 

Once point 2 has been addressed, I can move forward with the following, assuming the newly proposed definition meets with approval.

**new parent:** affinity evidence

**suggested new def.:** A type of affinity evidence based on an electrophoretic mobility shift of macromolecules, where proteins, nucleic acids, or both, are combined and the resulting mixtures are electrophoresed under native conditions through polyacrylamide or agarose gel to detect protein-nucleic acid interactions/complexes.

James

**Comment by beckyjackson** [comment]
@mgiglio99 @jbmunro - Can we follow up on this on the next call?

**Comment by mgiglio99** [comment]
I just emailed Pascale to get her thoughts on how to proceed on point #2 
For the new def, I like what you have James, but can we change the bit where it says "...protein-nucleic acid interactions..." - as that implies just those kind of interactions. How about either a) simply remove "protein-nucleic acid" or b) change it to "...to detect interactions/complexes between proteins and/or nucleic acids."

**Comment by mgiglio99** [comment]
For point number 2 - we posted a request for comments to the ECO tracker number 248) and announced the planned change on the GO Annotation tracker. Gave people two weeks to comment. No comments on either one. So we are moving ahead with the move.

**Comment by jbmunro** [comment]
New parent and modified definition.  Changes pushed to GitHub and available with the next release.  Closing this ticket.
