### ISSUE TITLE
Add DISPLAY_SYNONYM to terms

### ISSUE THREAD

**Issue by cmpich** [evidenceontology/evidenceontology#226]
Could we add DISPLAY_SYNONYM tags to the obo file which would contain the short names for the terms? We need to display the short names in our application but would like to use the ECO terms internally.

**Comment by rctauber** [comment]
Hi @cmpich - could you clarify what you mean by short names? Do you mean the short form of the IDs?

**Comment by cmpich** [comment]
I am talking about the code like:
IAGP
IEP
IDA
IC (inferred by curator)
etc...

**Comment by rctauber** [comment]
The GO codes are already listed as both synonyms and xrefs, for example for IC:

```
[Term]
id: ECO:0000305
name: curator inference used in manual assertion
def: "A type of curator inference that is used in a manual assertion." [ECO:MCC]
synonym: "IC" EXACT [GOECO:IC]
synonym: "inferred by curator" EXACT [GOECO:IC]
xref: GOECO:IC "inferred by curator"
```

**Comment by rctauber** [comment]
Please let us know if you need any other information on this issue. Thank you!

**Comment by cmpich** [comment]
Looking ok. Unfortunately, not all ECO codes have a short name but that probably is not your responsibility?

**Comment by rctauber** [comment]
Correct, only the ECO classes that map directly to a GO code have the short names

**Comment by mgiglio99** [comment]
Just jumping in for a quick comment - in fact we discourage the use of the short names, we only have the ones from the GO codes there because they predate ECO. We prefer that people display the ECO ids as identifiers for the ECO terms. We understand that for some applications there is a need to map to GO codes but we hope that the GO will ultimately adopt the use of native ECO ids.
