### ISSUE TITLE
Disconnect between GO documentation on IEA and its placement in ECO

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#251]
IEA is mapped to http://purl.obolibrary.org/obo/ECO_0000501

in ECO, this is a general class for any evidence that is used in an automatic assertion. This includes direct assays, e.g. as made by an automated device.

https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000501

![image](https://user-images.githubusercontent.com/50745/78280369-d0e4e180-74cd-11ea-8b5e-5a012a180bc1.png)

There is a disconnect between this and the *implicit* code-based ontology used by GO, where most people use IEA to mean "automated AND not experimental"

E.g.
http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)

_The IEA evidence code is used for annotations that are computationally, or automatically, assigned to gene products without further manual, curator review. IEA annotations are derived from two main pipelines: 1) manually constructed mappings between external classification systems and GO terms, and 2) automatic transfer of annotation to orthologous gene products._

Also
http://geneontology.org/docs/guide-go-evidence-codes/

States:

_‘Electronic’ (IEA) annotation are not manually reviewed (although the method itself is usually subjected to various quality assessments). IEA-supported annotations are ultimately based on either homology and/or other **experimental** or sequence information, but cannot generally be traced to an experimental source._

Formally this is a bit fuzzy; e.g "ultimately based on ... experimental information". Of course it's trivially true that the inference chain ultimately leads to experiments. I would prefer to change the language here. But in a pragmatic sense the *intent* is clear to anyone familiar with GO: IEA excludes experimental in GO.

This is clarified in the subsequent paragraph:

_The first, and most comprehensive, method is InterPro2GO, [...]. A second method is the computational conversion of UniProt controlled vocabulary terms [...]. Lastly, annotations are made based on 1:1 orthologs inferred from Ensembl gene trees, [...]._

I am a bit concerned that as GO makes the shift from GAF to GPAD and thus properly commits to ECO that we have not done enough work to properly align GAF codes and ECO, and that mentally the whole GO consortium is using a mental model that does not align with ECO

cc @pgaudet @vanaukenk @ukemi

**Comment by mgiglio99** [comment]
Hi @cmungall 
I agree - we have identified other similar issues with other terms. I fear it's going to be thorny to work these out. I'm not sure that all of the codes can be aligned to ECO terms in the way that GO may want. 
As for a specific reply to the IDA question above - I'll get back to this issue with some thoughts soon.

**Comment by ValWood** [comment]
Can't we just move GO  IEA -> ECO mapping down to "computational evidence used in manual assertion"  (I always thought it was that anyway)

**Comment by pgaudet** [comment]
Do you consider the assertions GO makes to be manual ?

**Comment by ValWood** [comment]
automatic- corrected

**Comment by ivanerill** [comment]
>Can't we just move GO IEA -> ECO mapping down to "computational evidence used in automatic assertion" (I always thought it was that anyway)

That seems like the logical way to go. Since its creation ECO has logically assumed that the evidence itself is separated from the assertion method, so both computational and experimental results can be automatically asserted (although automatic assertions for experimental evidence tend to be mostly high-throughput results). 

So IEA, in the sense that has been adopted by GO, is clearly not a good mapping to ECO:0000501, and the way to go would be to point it to ECO:0007669.

**Comment by pgaudet** [comment]
@kltm @alexsign

**Comment by mgiglio99** [comment]
This should work. The 'computational evidence' node was fairly recently added to ECO so didn't exist when the mappings were being made. There are issues with what terms should be children of computational evidence that we haven't sorted out yet, it's on our list - but for now, I think it makes sense to make this change. Just note that  because of the lack of sorted out children for this term, typical things that fall under IEA, like BLAST searches and HMM searches, will not currently slim up to the IEA-mapped term.

**Comment by kltm** [comment]
Tagging @cmungall

**Comment by cmungall** [comment]
Sounds like we are good with Val's amended suggestion "IEA == computational evidence used in automatic assertion"

@mgiglio99 points out an issue:

> Just note that because of the lack of sorted out children for this term, typical things that fall under IEA, like BLAST searches and HMM searches, will not currently slim up to the IEA-mapped term.

yes, you are right, this doesn't slim up 
https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000209&viewMode=All&siblings=false

but why?

or more specifically, why isn't BLAST evidence (https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000206) under computational evidence? I guess I could theoretically do BLAST on pen and paper without a computer.... but really it should be computational, no?

All: I think it would be worthwhile doing a review of all GAF codes, as in properly checking the true path rule holds

**Comment by mgiglio99** [comment]
@cmungall 
Short answer as to why isn't blast a child of computational - we simply haven't gotten around to doing it yet. And we encountered some challenges when we started working on it that we needed to resolve. 

As for reviewing all of the GAF codes - absolutely this is a good idea. And like I said above, we know of a couple changes that we want to make in ECO that will effect the mappings. And we know of a couple changes we have already made that effected the mappings that we've dealt with in an ad hoc way up until now and for which we have a more permanent plan, but haven't implemented it yet.

@cmungall Is there a timeframe for the shift from GAF to GPAD and use of native ECO? 
I didn't realize this was happening imminently (although I'm happy for that to happen). Challenge for me is that people on the ECO team have competing deadlines in other projects (unrelated to ECO) to deal with at the moment. And I will need to carve out some time to devote to this - please let me know.

@nsuvarnaiari @jbmunro @beckyjackson

**Comment by mgiglio99** [comment]
@cmungall, @ValWood , @ivanerill , @nsuvarnaiari 
Apologies for the delay in getting back to this.
In looking at this some more I realize that I should have noted earlier in this discussion that in the gaf-eco-mapping-derived file, all of the things you would expect to slim to IEA already do - all of the computational sequence based stuff etc. Even though the sequence based terms were not a child of 'computational evidence'. And since the derived file is what people should be using for mapping granular terms up - then everything should have been ok from that standpoint, even when we last discussed this.

The problem remains that experimental evidence used for automated assertions, should not be mapping to IEA. We will fix that by removing those. (**Action Item**) Those terms in the form 'experimental evidence used in automatic assertion' will then not map to any GO ev code - does that sound correct?

Also, we need to fix the separate issue in the gaf-eco-mapping file (that just lists the "equivalencies" between ECO terms and GO ev codes) of the default mapping of IEA - I think we have all agreed that it should be to ECO:0007669 'computational evidence used in automatic assertion' (instead of ECO:0000501 'evidence used in automatic assertion').  
That's easy to fix. We will do that. (**Action Item**)
I will also do the same substitution in the GO_REF/IEA combinations located in that file and review them all to make sure they look ok. (**Action Item**)

Also want to let you know that we've changed the way that we generate the derived mapping file. The new way allows us to curate the GO ev code that should be mapped to ECO at the term level. (The old way we did this would gather descendents of the default "equivalence" mapped ECO terms - however, we've run into issues with that when ECO shifts a term to a location that isn't consistent with the GO use of an ev code. ) 

Also we are going to make the whole sequence similarity branch a child of computational evidence (ultimately, if not initially,  an inferred child). (**Action Item**) (But that won't effect the mappings in the gaf-eco-mapping-derived file which have been mapping correctly all along.)

**Comment by ivanerill** [comment]
>In looking at this some more I realize that I should have noted earlier in this discussion that in the gaf-eco-mapping-derived file, all of the things you would expect to slim to IEA already do - all of the computational sequence based stuff etc. Even though the sequence based terms were not a child of 'computational evidence'. 

>Also we are going to make the whole sequence similarity branch a child of computational evidence (ultimately, if not initially, an inferred child). (Action Item) (But that won't effect the mappings in the gaf-eco-mapping-derived file which have been mapping correctly all along.)

A caveat here is that many "computational evidence" terms may be used with "manual assertion" (e.g. manually reviewing BLAST results to conclude that a protein sequence is homologous to another and assigning it function), and I believe those terms should not map to IEA.

**Comment by mgiglio99** [comment]
@ivanerill 
Absolutely correct. And that is the way it is now and will continue to be. 
The computational manual assertion terms map to things such as ISS.

**Comment by mgiglio99** [comment]
@cmungall @ValWood 
As we started looking at this, we wondered about the 'high throughput evidence used in automatic assertion' branch and its children. Should they stay mapped to IEA?

**Comment by ivanerill** [comment]
I believe it makes sense, even if they are not computational methods (the
automatic assertion is, in some way, computational). I don't know how these
are currently handled with GO evidence codes.

**Comment by ValWood** [comment]
> As we started looking at this, we wondered about the 'high throughput evidence used in automatic assertion' branch and its children. Should they stay mapped to IEA?

These  should map to HTP ? https://pubmed.ncbi.nlm.nih.gov/30715275/
Actually, I don't know what that code means, do you have an example? The 'high throughput evidence' implies experimental, but automatic assertion implies computational.
Does it have descendants?

Anyway for all HTP experimental we use HTP , and for purely computational we  use IEA

**Comment by ValWood** [comment]
edited my comment above for clarity (I hope!)

**Comment by mgiglio99** [comment]
Yes, currently all of the manual assertion HTP terms are mapping to HTP or one of the more specific high-throughput evidence codes.
We will map all of the automatic assertion high-throughput terms to IEA.

**Comment by mgiglio99** [comment]
We've accomplished all of the above Action Items, and hearing no additional objections or concerns, we are closing this issue. Please reopen if a new concern arises.
Michelle
