### ISSUE TITLE
ECO_0001105 : nmr evidence is not always for structure elucidation

### ISSUE THREAD

**Issue by bjonnh** [evidenceontology/evidenceontology#261]
NMR evidence can be used for structure elucidation yes, but it can also be used for quantification (which does not require structure elucidation) and many other things.
So either we need to move that term outside of ECO_0005031 or we need to split it in two terms:
"nuclear magnetic resonance spectroscopy for structure determination evidence"
"nuclear magnetic resonance spectroscopy for quantification evidence"
"nuclear magnetic resonance spectroscopy evidence"

**Comment by mgiglio99** [comment]
Hello @bjonnh 
Thanks for alerting us to this. We feel the simplest solution is to broaden the def of ECO_0005031 and move it out to be a child of 'experimental evidence'.

Proposed new def: A type of experimental evidence that uses the magnetic properties of atomic nuclei for quantification of metabolites or for the determination of chemical structure or composition.

@pgaudet  - This is one of the terms in the set that you worked with Marcus on. Does this new definition above work for you? And are you ok with moving it out from under 'structure determination evidence'?
Old def: "A type of structure determination evidence resulting from the use of an MRI to provide chemical information about tissue metabolites."

**Comment by bjonnh** [comment]
Oh if this was covering MRI as well, then the new definition doesn't work… 

We probably need another term for MRI evidence as it is both a different approach and provide different kind of results, usually imaging based, but there may be other uses I am not aware of.

**Comment by mgiglio99** [comment]
Yes, that issue with MRI occurred to me too. In my reading of the old def, I think it was not really including imaging - my plan was to make a separate term for that. 
I forgot to mention this in my last post.
@pgaudet - is that consistent with your understanding/use of the old term?

**Comment by mgiglio99** [comment]
@bjonnh and @pgaudet

In looking at this some more, Suvvi and I propose a new structure. We want to make a parent for all nuclear magnetic resonance evidence with specific children for MRI and NMR spectroscopy. Because the definition of the existing term "nuclear magnetic resonance spectroscopy" ECO:0001105 seems to combine aspects of both of these uses of MRI, we want to make that term the NMR evidence parent. Then we will make two new children for the specific types as follows:

-experimental evidence
---nuclear magnetic resonance evidence ECO:0001105 
-----magnetic resonance imaging evidence (ECO:new)
-----nuclear magnetic resonance spectroscopy evidence (ECO:new)
-------heteronuclear single quantum coherence spectroscopy evidence ECO:0001813

Definitions:
**nuclear magnetic resonance evidence:** "A type of experimental evidence in which atomic nuclei in a strong constant magnetic field are perturbed by a weak oscillating magnetic field and the resulting electromagnetic signal is captured." (wikipedia)
**magnetic resonance imaging evidence:** "A type of nuclear magnetic resonance evidence used to image anatomy and physiological processes."
**nuclear magnetic resonance spectroscopy evidence:** "A type of nuclear magnetic resonance evidence used for quantification of metabolites or for the determination of chemical structure or composition."

Please let us know what you think of this proposal.

**Comment by bjonnh** [comment]
That would work perfectly for me and that would allow people doing relaxometry to also add their terms if ever needed.

**Comment by pgaudet** [comment]
Looks good to me too, thanks

**Comment by mgiglio99** [comment]
ok great!
We will implement.
Thanks to both of you.

**Comment by nsuvarnaiari** [comment]
Hi @bjonnh 

As per the discussions in this thread, the following new terms have been added and are available in today's ECO release.

experimental evidence
---nuclear magnetic resonance evidence ECO:0001105
-----magnetic resonance imaging evidence (ECO:0006166) -NEW
-------magnetic resonance imaging evidence used in manual assertion (ECO:0006168) - NEW
-------magnetic resonance imaging evidence used in automatic assertion (ECO:0006167) - NEW
-----nuclear magnetic resonance spectroscopy evidence (ECO:0006163) - NEW
-------nuclear magnetic resonance spectroscopy evidence used in manual assertion (ECO:0006165) - NEW
-------nuclear magnetic resonance spectroscopy evidence used in automatic assertion (ECO:0006164) - NEW
-------heteronuclear single quantum coherence spectroscopy evidence ECO:0001813

Thanks,
Suvvi

**Comment by bjonnh** [comment]
Thank you so much!
