### ISSUE TITLE
Advice needed: EM as evidence for protein-protein interaction

### ISSUE THREAD

**Issue by tberardini** [evidenceontology/evidenceontology#272]
Hi there,  We have a user who would like to submit protein-protein interaction data using electron microscopy (EM) as the evidence.  

He says: "I recommend to add this method, because, due to the dramatically increased resolution of single particle cryoEM, future information on protein:protein interactions will largely come from EM studies."

https://academic.oup.com/plcell/advance-article/doi/10.1093/plcell/koab092/6188636

Right now, ECO:0006003 electron microscopy evidence used in manual assertion falls under direct assay (GO IDA) and not physical interaction (GO IPI).  For GO, if we capture the annotation as IDA, we cannot capture the partner, that will error out upon annotation QC.  

Can you advise?

@cmungall Maybe you have some thoughts on how to solve?

**Comment by mgiglio99** [comment]
Hi Tanya,
Coincidentally, we are planning a new 'cryogenic EM' child of EM based on requests of another group - that will be going into ECO with the next release.

Options:
1. Change ECO's GO mapping of 'cryoEM' to IPI - we can't do this option since cyroEM is used for many things other than physical interactions.
2. Make a term for 'cryogenic EM-based protein-protein interaction evidence' under two parents: 'physical interaction evidence' (GO IPI) and 'cryogenic EM'. 
This option concerns us because it can lead to these combinatorial terms for every way that any method is used for any particular type of evidence. And it has asserted dual parentage, which we understand we should try to avoid. This relates to a constant struggle we have in ECO regarding methods vs. biological context of evidence, which we haven't quite solved. (We are considering a realignment of ECO that would use logical relationships to infer the combined methods and context - but that is still in the thinking phase.)
3. Change the GO rules to allow a partner under IDA.
This way the annotation can be made with just 'cryoEM' even though that doesn't map to IPI.

Not surprisingly - we like number 3 best!  :)
Might be good to have a chat with @cmungall about option 2 and it's ramifications.

**Comment by tberardini** [comment]
Yup, definitely need input from @cmungall and also @pgaudet and @vanaukenk.

**Comment by mgiglio99** [comment]
To give an example of what we mentioned parenthetically above in number 2, we are thinking of treating this kind of thing as we do the manual and automatic assertion terms by inferring the relationships.
Thus, we might do something like one of these:
'protein-protein interaction evidence based_on cryoEM evidence'
where this term would have a logical equivalence:
protein-protein interaction evidence and _based_on_ some cyroEM
OR
'cryoEM evidence used_in protein-protein interaction evidence'
also with a logical equivalence

But we still have to think about this a lot more....

**Comment by pgaudet** [comment]
I agree that IPI and IDA can be overlapping, so the parentage is problematic. 

At some point @vanaukenk and I had discussed using only IDA in GO, and drop the use of IPI. Currently in GO rules are set up as follows: 
- GORULE:0000007 IPI should not be used with GO:0003824 catalytic activity or descendants
- GORULE:0000018 IPI annotations require a With/From entry
- 
but we could organize this differently and require a with/from for annotations to binding or protein binding, and allow it or any IDA. 

I think we had not gone further with the idea because it involved a significant change in annotation practices, but if there is a reason in ECO to do it, we could reconsider?

Thanks, Pascale

**Comment by vanaukenk** [comment]
If we go the route of populating With/From for IDA binding annotations, I think we'll need to make this permissive rather than required, i.e. for binding terms that use an IDA evidence code, a value in With/From is allowed.

There are existing IDA annotations to some binding terms, e.g. actin binding, because it wasn't possible to capture a specific binding partner id in the With/From field.

**Comment by pgaudet** [comment]
Even for direct annotations to 'GO:0005488 binding' and 'GO:0005515 protein binding'?

**Comment by vanaukenk** [comment]
'GO:0005488 binding' is a 'do not annotate' anyway, right?

For 'GO:0005515 protein binding' and IDA, the curator should have an id for the With/From field, so maybe requiring it there would be okay.

But I am concerned this is becoming too complicated.....

**Comment by pgaudet** [comment]
We can have this discussion outside this tracker - the question was, could GO do without IPI? We will need to notify contributing groups in advance if we change our practices.

**Comment by mgiglio99** [comment]
Hi - we're going to close this one for now. If changing the GO rules for IPI/IDA didn't work out - please re-open and we can again try to find a solution.
