### ISSUE TITLE
NTR: colony boundary assay evidence

### ISSUE THREAD

**Issue by dsiegele** [evidenceontology/evidenceontology#273]
suggested definition: 
A type of experimental phenotypic evidence based on the presence or absence of a visually apparent boundary formed between two isolates or strains of the same microbial species-level taxon growing on a solid surface such as that of an agar culture medium.

The assay is described in PMID:18621670

Example of how the assay is used: When different isolates of Proteus mirabilis are grown on the same agar plate, a boundary will be visible boundary between the colonies of some isolates, while the colonies of other pairs of isolates merge together. Isolates that merge are considered to belong to the same strain, whereas isolates that don't merge are considered to belong to different strains of Proteus mirabilis.

**Comment by mgiglio99** [comment]
Hi Debby,
We have a couple of suggestions:
1. We think this should be a child of 'colony morphology phenotypic evidence', rather than 'experimental phenotypic evidence' (which is actually a parent of 'colony morphology phenotypic evidence')
2. We would revise the definition accordingly and also add in that this is happening with colonies as so:
"A type of colony morphology phenotypic evidence based on the presence or absence of a visually apparent boundary formed between colonies of multiple isolates or strains of the same microbial species growing on a solid surface such as that of an agar culture medium."

Would these changes be ok?

**Comment by dsiegele** [comment]
Hi Michelle,

These changes seem fine to us!  Thank you!

**Comment by mgiglio99** [comment]
Sounds good Debby - we'll have this term out in the next release.

**Comment by nsuvarnaiari** [comment]
Hi @dsiegele 

This new term is now publicly available in today's ECO release.

Name: colony boundary assay evidence
ECO id: ECO:0006240
Parent ECO Id: ECO:0007077 (colony morphology phenotypic evidence)

Closing the ticket, but pls reopen if needed.
Thanks,
Suvvi
