### ISSUE TITLE
DisProt terms Batch 2

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#277]
Next set of terms, noted below the yellow bar in the following spreadsheet:
https://docs.google.com/spreadsheets/d/1SP4wn4mJC2eZBR0sPNcKZNq5-ocwBEO6tlKJHnEL514/edit?usp=sharing

**Comment by nsuvarnaiari** [comment]
Hi Balint/ Federica,

Batch2 terms are now available in eco-edit.owl file. They will be publicly available after Aug release.
Here is the list of 28 new terms in batch2 and their ECO ids,
| ECO IDs     | New Term Label                                                                           |
|-------------|------------------------------------------------------------------------------------------|
|ECO:0006247|analytical ultracentrifugation evidence|
|ECO:0006248|fluorescence polarization evidence|
|ECO:0006249|bait-prey protein pull-down evidence|
|ECO:0006250|rotary shadowing electron microscopy evidence|
|ECO:0006251|electrospray ionization fourier transform ion cyclotron resonance mass spectrometry evidence|
|ECO:0006252|magnetic resonance evidence|
|ECO:0006253|electron paramagnetic resonance evidence|
|ECO:0006254|site-directed spin-labelling electron paramagnetic resonance evidence|
|ECO:0006255|deglycosylation assay evidence|
|ECO:0006256|protein fragment functional complementation evidence|
|ECO:0006257|beta galactosidase functional complementation evidence|
|ECO:0006258|GAL4-VP16 functional complementation evidence|
|ECO:0006259|Raman spectroscopy evidence|
|ECO:0006260|protein thermal shift assay evidence|
|ECO:0006261|microscale thermophoresis evidence|
|ECO:0006262|native protein gel electrophoresis evidence|
|ECO:0006263|turbidity measurement evidence|
|ECO:0006264|competitive binding evidence|
|ECO:0006265|protein unfolding evidence|
|ECO:0006266|urea-induced protein unfolding evidence|
|ECO:0006267|pH-induced protein unfolding evidence|
|ECO:0006268|temperature-induced protein unfolding evidence|
|ECO:0006269|cell aggregation evidence|
|ECO:0006270|RNA-protein binding evidence|
|ECO:0006271|fluorescence microscopy evidence|
|ECO:0006272|viscosity measurement evidence|
|ECO:0006273|dynamic fluorescence quenching evidence|
|ECO:0006274|static fluorescence quenching evidence|

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Pushed batch2 terms in our ECO release that was completed today 08/12/2021. We have changed the label for existing term “hybrid interaction evidence” to “bait-prey hybrid interaction evidence” (ECO:0000025) and moved it to be a child of “protein binding evidence”. We have obsoleted the term that was created for DisProt before – “bait-prey protein pull-down evidence” (ECO:0006249) as it is same as “hybrid interaction evidence” . But added the label "bait-prey protein pull-down evidence" as a synonym to “bait-prey hybrid interaction evidence”.
 
So batch2 now has 27 new terms instead of 28 (due to obsoletion of bait-prey protein pull-down evidence).
