### ISSUE TITLE
ECO tree view in ECO browser not displaying the tree for searched terms

### ISSUE THREAD

**Issue by nsuvarnaiari** [evidenceontology/evidenceontology#288]
@suzialeksander reported that tree view is not displaying the tree for a searched term "ECO:0007295" - inference by association of genotype from phenotype used in automatic assertion. Instead "Loading" is displaying. Trying different terms yield the same "Loading" message.

Interestingly, the tree loads and can be traversed by clicking [+] or [-] and the tree displays for terms 'evidence' and 'assertion method'.

@mgiglio99 @dolleyj

**Comment by mgiglio99** [comment]
Hi Dustin,
Just checking on this issue. We saw the comments on other issue Suvvi created at OLS. Do you think this is a quick fix? If not, I'm thinking that we should just put our web site's code on ice for now and have the website link to OLS directly. Then later, if we get funding, we can address things more fully. 
Let us know your thoughts.
Thanks

**Comment by dolleyj** [comment]
@mgiglio99, It took me a bit to get reacquainted with this. This issue stems from us filtering out non-ECO terms so we only display ECO terms in the tree. If we want to continue filtering out non-ECO terms, this is not a quick fix and we should go with the solution you proposed. 

I do have an alternative to offer and please let me please your thoughts on this. We could forego the filtering for now so that all terms are displayed on the tree. This would allow the tree to work, and should funding be awarded, we can always revisit the filtering then. I would expect this to be a quick turnaround.

**Comment by mgiglio99** [comment]
Hi Dustin,
Your idea sounds good. My only worry is that I'm not sure how the tree will look if we do that. But let's try it.
Thanks,
Michelle

**Comment by dolleyj** [comment]
Hi @mgiglio99, I deployed the change to our staging site. Please let me know your thoughts after you have a chance to review it.
Thanks,
Dustin

**Comment by nsuvarnaiari** [comment]
Hi Dustin,

The tree seems to be not loading still. Eg: ECO:0007295.

Thanks,
Suvvi

**Comment by dolleyj** [comment]
I deployed the tree to production. It is no longer trying to filter out non-ECO terms. It is now working as expected. Closing ticket.
