### ISSUE TITLE
Change ECO toGO mappings for biological reconstruction evidence terms

### ISSUE THREAD

**Issue by pgaudet** [evidenceontology/evidenceontology#289]
Hi, 

biological reconstruction evidence terms mappings to GO evidence codes are inconsistent, as pointed out in another ticket  #262 

@alexsign and I propose the following mappings: 
* ECO:0005542	biological system reconstruction evidence by experimental evidence from single species used in manual assertion	=> EXP
* ECO:0005543	biological system reconstruction evidence by experimental evidence from mixed species used in manual assertion	=> EXP
* ECO:0005547	biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion	=> NAS
* ECO:0005610	biological system reconstruction evidence based on homology evidence used in manual assertion	=> ISS
* ECO:0005546 biological system reconstruction evidence based on paralogy evidence used in manual assertion	=> ISS
* ECO:0005544 biological system reconstruction evidence based on orthology evidence used in manual assertion	=> ISO

Thanks, Pascale

**Comment by pgaudet** [comment]
@vanaukenk

**Comment by mgiglio99** [comment]
Hi @pgaudet
We'll need to hear from the Complex Portal folks to see if these will work.
Note that we would still need a GO mapping for the 'biological system reconstruction evidence used in manual assertion' term.
They mostly look fine to me, but I think ECO:0005547 'biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion' should map to IC not to NAS. But I realize that would recreate the with/from problem for that one.
Is there any chance of GO allowing a GO_ref there? Or making it a warning instead? 

looping in @bmeldal, @sandraorchard since they were on the original issue

**Comment by mgiglio99** [comment]
Here is a summary of where things stand (at least where I think they stand):
Pascale suggested the following mappings - I have added notes about ECO's thoughts on those suggestions.

- ECO:0005542 biological system reconstruction evidence by experimental evidence from single species used in manual assertion => EXP
ECO: sounds good

- ECO:0005543 biological system reconstruction evidence by experimental evidence from mixed species used in manual assertion => EXP
ECO: sounds good

- ECO:0005547 biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion => NAS
ECO: we prefer IC as a mapping for this one but if GO and Complex Portal are happy with NAS, that's fine.

- ECO:0005610 biological system reconstruction evidence based on homology evidence used in manual assertion => ISS
ECO: sounds good

- ECO:0005546 biological system reconstruction evidence based on paralogy evidence used in manual assertion => ISS
ECO: sounds good

- ECO:0005544 biological system reconstruction evidence based on orthology evidence used in manual assertion => ISO
ECO: sounds good

One that wasn't in Pascale's list is the parent manual term: ECO:0007746 biological system reconstruction evidence used in manual assertion
For this one we also think IC is the best mapping, but we realize that will still cause problems. Do you want NAS for this one too?

@bmeldal  @sandraorchard

**Comment by pgaudet** [comment]
Hi @mgiglio99 

I just checked with  @sandraorchard  and she agrees to use NAS for ECO:0007746 biological system reconstruction evidence used in manual assertion. 

For now, we need to move all these under a parent other than IC, because there is a conflict with the GO rule that requires a GO term as supporting evidence for IC annotations.  The biological reconstruction assays is not being supported by another GO term, so that cannot be done for these annotations. 

Maybe the problem is with the IC itself, there could be a more specific IC for GO (or a more general parent of IC). 

If you dont mind doing this fix for now, that will allow Protein2GO curators to use IC again. We should schedule a time to revisit this, and other GO-ECO alignment issues. It may make sense to leave this ticket open until we have a better solution.

Thanks, 

Pascale

**Comment by mgiglio99** [comment]
Hi @pgaudet, @sandraorchard

I understand the problem with the GO rule regarding IC needing a GO term in the with field - which is why we have mapped all of the relevant manual assertion terms to ISS, EXP, etc. as above. However, your suggestion that we  "move all these under a parent other than IC" implies that you are not using the direct mappings we just agreed on above, but rather that you are using the ECO hierarchy to map. Is that the case?  
If so, we request that you stop doing that.

As we have said in the past, we have created the "has GO evidence code" annotation property for the terms to capture the mapping to GO. And we will now update the contents of that field with the mappings above. Also we produce the "gaf-eco-mapping.derived" files from the information in that field as well. All of this will be updated and ready for your use with the next ECO release (soon).

**Comment by pgaudet** [comment]
Ha! Thanks for the information. I think we *do* use the hierarchy. 


to be confirmed by @alexsign
@dustine32


Thanks, Pascale

**Comment by pgaudet** [comment]
@kltm

**Comment by alexsign** [comment]
@pgaudet yes we do

**Comment by dustine32** [comment]
@pgaudet [As of this May](https://github.com/biolink/ontobio/issues/623), when converting ECO code to a GAF evidence code, the GO pipeline now refers to http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt _if_ the ECO code is not in the direct mapping file at http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt.

Both files are generated by ECO and we assume they use the hierarchy to construct `gaf-eco-mapping-derived.txt`.

**Comment by mgiglio99** [comment]
Hi all, 
We do **NOT** use the hierarchy to generate the two mapping files above. We used to do that prior to last fall, however, we changed the procedure specifically because GO evidence codes sometimes combine things that are in different branches in ECO and vice versa which makes hierarchical mapping problematic. We are glad to hear that the GO pipeline is now using those two mapping files. That makes me very happy! 
**Question**: is the pipeline that @alexsign is referring to different than the one that @dustine32 is referring to?

We regenerate the gaf-eco-mapping-derived.txt file from the full ECO with every release and thus new mappings stored in the "has GO evidence code" annotation property for any term will get included in each new release version of the mapping file.
The above mappings for the manual assertion children of the 'biological system reconstruction evidence' node will be entered into ECO with our next release. The next release will happen by the end of July. (We missed doing a June release due to other pressing deadlines.)

**Comment by dustine32** [comment]
@mgiglio99 Ah, thanks for clarifying! We were planning on eventually [parsing the ECO ontology](https://github.com/biolink/ontobio/issues/624) but that will now be on hold if not entirely dropped. I'll link to your comment.

I was referring to the GO release pipeline that produces the annotation/ontology files available here: http://current.geneontology.org/. I think this is a different pipeline than the one @alexsign referred to.

**Comment by mgiglio99** [comment]
Hi all,
Summary, question, and reminder below:

**We will make these mapping changes:**
- ECO:0005542 biological system reconstruction evidence by experimental evidence from single species used in manual assertion => EXP
- ECO:0005543 biological system reconstruction evidence by experimental evidence from mixed species used in manual assertion => EXP
- ECO:0005547 biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion => NAS
- ECO:0005610 biological system reconstruction evidence based on homology evidence used in manual assertion => ISS
- ECO:0005546 biological system reconstruction evidence based on paralogy evidence used in manual assertion => ISS
- ECO:0005544 biological system reconstruction evidence based on orthology evidence used in manual assertion => ISO

**Question on this one that was not in Pascale's original list:**
ECO:0007746 biological system reconstruction evidence used in manual assertion
For this one we think IC is the best mapping, but we realize that will still cause problems. Do you want NAS for this one too? **Let us know.**

**One final reminder:** don't use the ECO hierarchy to map granular ECO terms to GO evidence codes; instead use the two mapping files -  http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt if the ECO code is not in the direct mapping file at http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt - OR - use the "has GO evidence code" annotation property in the ontology to get correct mappings.

**Comment by nsuvarnaiari** [comment]
Hi All,

The following changes have been pushed in today's release. Please let us know if they break things at your end.

- ECO:0005542 biological system reconstruction evidence by experimental evidence from single species used in manual assertion => EXP
- ECO:0005543 biological system reconstruction evidence by experimental evidence from mixed species used in manual assertion => EXP
- ECO:0005547 biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion => NAS
- ECO:0005610 biological system reconstruction evidence based on homology evidence used in manual assertion => ISS
- ECO:0005546 biological system reconstruction evidence based on paralogy evidence used in manual assertion => ISS
- ECO:0005544 biological system reconstruction evidence based on orthology evidence used in manual assertion => ISO
- ECO:0007747 biological system reconstruction evidence by experimental evidence used in manual assertion => EXP
- ECO:0007746 biological system reconstruction evidence used in manual assertion => NAS

The mappings are now in http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt file. (NOTE: You will not get these mappings if you use ECO hierarchy but by using the "has GO evidence code" annotation property in the ontology or the gaf-eco-mapping-derived.txt file)

Thanks,
Suvvi

**Comment by mgiglio99** [comment]
@pgaudet 
won't the with/from problem that was coming up for IC also come up for ISS and ISO mappings - that is, needed something in the with field? Or do ComplexPortal annotations have something that works for ISS/ISO, but just not a GO term which was needed for IC?

**Comment by pgaudet** [comment]
Hi @mgiglio99 

Most of the annotations are to 

ECO:0005547              biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion | 96.06 | 25,060

There are 808 to [ECO:0005610](https://www.ebi.ac.uk/QuickGO/term/ECO:0005610)
biological system reconstruction evidence based on homology evidence used in manual assertion  (and 220 [ECO:0005543](https://www.ebi.ac.uk/QuickGO/term/ECO:0005543) biological system reconstruction evidence by experimental evidence from mixed species used in manual assertion


Annotations to 'biological system reconstruction evidence based on homology evidence used in manual assertion' do need a value in the 'with', if they don't have it, it would be correctly filtered by the GO QCs. 

@sandraorchard

**Comment by mgiglio99** [comment]
Thus the mapping solutions above won't entirely fix the problem for ComplexPortal.
So, what are our options?
-Change the mapping again
-Change the GO rules
I feel like as time goes by, these more nuanced cases might keep cropping up - annotations that don't fit nicely into the current GO rules but which make sense to have and use. Worth considering?
