### ISSUE TITLE
NTRs: additional machine learning method evidence and assertion terms

### ISSUE THREAD

**Issue by vanaukenk** [evidenceontology/evidenceontology#307]
Hi,

We are working on developing a new literature system for the Alliance of Genome Resources, known as the ABC, and were excited to see the [addition of new ECO codes](https://github.com/evidenceontology/evidenceontology/issues/301) describing various machine learning methods as AI will be an important component of the system.

The ABC will track entities (e.g. genes, variations, etc.) and topics (e.g. phenotypes, genetic interactions, etc.) mentioned and studied in references, as determined by humans (biocurators and authors) as well as machine learning methods.

It will be important for us to track the type of machine learning method, so we’d like to request some additional ECO codes to do this.  (It will also be important for us to try to track what ‘role’, e.g. author, biocurator, a human plays in the assertion; I will put that proposal in another ticket.)

For additional machine learning codes, we’d love to have:

machine learning method evidence (ECO:0008000)
- support vector machine evidence (ECO:new)

Proposed definition: A type of machine learning method evidence that uses a supervised learning model with associated algorithms for classification.  Support vector machines aim to determine a hyperplane that separates two classes while maximizing the distance from the hyperplane to any given data point in those classes.
Reference: https://www.nature.com/articles/nbt1206-1565
Synonym (EXACT): SVM evidence

machine learning method evidence (ECO:0008000)
- rule-based machine learning method evidence (ECO:0008002)
-- string-matching method evidence (ECO:new)

Proposed definition: A type of rule-based machine learning evidence in which patterns or strings (e.g. text) are identified within a larger string or body of text.
Reference: https://en.wikipedia.org/wiki/String-searching_algorithm
Synonym (EXACT): string-searching method evidence

machine learning method evidence (ECO:0008000)
- rule-based machine learning method evidence (ECO:0008002)
-- regular expression method evidence (ECO:new)

Proposed definition: A type of string-matching method evidence in which patterns consisting of characters and/or symbols in combination are used to identify matches in a larger string or body of text.
Reference: https://en.wikipedia.org/wiki/Regular_expression
Synonym (EXACT): regex method evidence
Synonym (EXACT): regexp method evidence

And for the new assertion terms:

machine learning method evidence used in automatic assertion (ECO:0008004)
- deep learning method evidence used in automatic assertion (ECO:0008006)

Question: Is ECO:0008006 just intended to represent neural networks? If so, can we add 'neural network method evidence' as an exact synonym? If not, we would like to request a more specific deep learning method evidence child term strictly for neural networks, and I can update this ticket with that info.

machine learning method evidence used in automatic assertion (ECO:0008004)
- support vector machine method evidence used in automatic assertion (ECO:new)

Proposed definition: A type of support vector machine learning evidence that is used in an automatic assertion.

machine learning method evidence used in automatic assertion (ECO:0008004)
- rule-based machine learning method evidence used in automatic assertion (ECO:0008008)
-- string-matching method evidence used in automatic assertion (ECO:new)

Proposed definition: A type of string-matching method evidence that is used in an automatic assertion.

machine learning method evidence used in automatic assertion (ECO:0008004)
- rule-based machine learning method evidence used in automatic assertion (ECO:0008008)
-- regular expression method evidence used in automatic assertion (ECO:new)

Proposed definition: A type of regular expression method evidence used in an automatic assertion.

Please let us know if we can clarify anything or if you'd like to discuss these NTRs on a call.

Many thanks,
--Kimberly

@cerivs @valearna @azurebrd

**Comment by vanaukenk** [comment]
@mgiglio99 @nsuvarnaiari 

Hi - wondering if you might have some time in the coming weeks to take a look at this ticket and #308 for work we are doing at the Alliance.

Let me know if it'd be helpful to chat in person.

Thanks,
--Kimberly

**Comment by nsuvarnaiari** [comment]
Hi @vanaukenk,

Sorry for a late response. Michelle just got back from vacation and I am still on a 3 week vacation. I should be able to work on the terms after I return to office on July 10th.

Thanks,
Suvvi

**Comment by vanaukenk** [comment]
Great; thanks @nsuvarnaiari !!

**Comment by mgiglio99** [comment]
Apologies on the delay for these. 
Haven't forgotten you and will be addressing them soon.

**Comment by vanaukenk** [comment]
Thanks @mgiglio99
Let us know if you'd like to set up a time to chat about them.
We'd be happy to explain more about what we're trying to model and why we'd like the new codes, and get your feedback.

**Comment by mgiglio99** [comment]
H Kimberly,

Just a few notes in advance of our meeting tomorrow....

The support vector machine term seems very straightforward - I think that one can go right in.
We will generate both manual assertion and automatic assertion child terms of the new svm term. (That is our general policy - all evidence type terms get both of those children.)

Regarding your question on ECO:0008006 - I did some more reading on this. I think we might need to rearrange some terms here. I think there are neural networks that are not deep learning - that is when it has 3 or less layers. Once a network has more than 3 layers then it is "deep". So I'm now thinking perhaps we need a neural network parent term for deep learning. I think we didn't do that before because it would have created a parent with a single child but we need both neural network and deep learning.
Perhaps it would be this structure:
machine learning method evidence (ECO:0008000)
--neural network method evidence (new)
----deep learning neural network method evidence (slight change to the name of the current ECO:0008001)
All of these would have manual and automatic assertion children.
Would that work for you?

I'm a little less clear on the two proposed terms for pattern matching: 
'string-matching method evidence'
'regular expression method evidence'
I don't feel like these are a kind of machine learning. How would you feel about a new child of 'computational evidence' called 'pattern matching evidence'?
It could then have your two new terms as children.

Looking forward to chatting tomorrow.

Best,
Michelle

**Comment by esperetta** [comment]
Hi Michelle and Kimberly, 
I hope you are both well and you don't mind me to chip in the conversation. 

If you are changing some part of the tree, could you please confirm that the ECO codes numbers will still remain the same? Asking because next UniProt release (September) will be already using "ECO:0008006"	(deep learning method evidence used in automatic assertion") to describe one of our deep learning data type and we would prefer not to do change this.

Also, when we proposed the terms for deep learning, we also had a version [in the ticket](https://github.com/evidenceontology/evidenceontology/issues/301) similar to the one Michelle was considering above. Eventually we chose a shorten/flatter version as it seemed most neural networks are actually deep learning these days.

Many thanks! 
Elena (on behalf of UniProt)

**Comment by mgiglio99** [comment]
@esperetta - always happy for you to chip in to the conversation. : )
The ECO ids for existing terms will stay the same - your terms will still be just as they are now. And regarding neural network terms, I was remembering our discussion about this and our desire not to make a term with only one child, but in the end we decided that we should reflect that not all neural networks are deep learning and provide the ability for someone to use that term alone, and also for there to be additional neural network children in addition to deep learning. 

@vanaukenk and AGR - 
As I started to finalize things, some additional things occurred to me:
1. In your proposal you placed string matching and regular expressions terms both directly under rule-based machine learning (which I know we decided to change to computational evidence) as siblings, however, I notice that you defined regular expressions as a type of string matching.Therefore, in the structure below I made regular expressions a child of string matching.
2. I started to make the parent term 'pattern matching evidence' like we talked about during the call, however, I kept coming up with definitions that were not significantly different than the def for string matching. And when I tried to broaden it, I felt I started to get into territory handled by other term nodes such as sequence alignment. Therefore I decided just to make string matching a direct child of 'computational evidence'. Let me know if that sounds ok.

**New terms:**
(copied from what you proposed above)
ECO:new 'support vector machine evidence'
Proposed definition: A type of machine learning method evidence that uses a supervised learning model with associated algorithms for classification. Support vector machines aim to determine a hyperplane that separates two classes while maximizing the distance from the hyperplane to any given data point in those classes.
Reference: https://www.nature.com/articles/nbt1206-1565
Synonym (EXACT): SVM evidence

(revised from what you proposed)
ECO:new 'string-matching method evidence'
Def: A type of computational evidence that employs a string algorithm to identify a string within a larger string or body of text, where a string is a particular series of characters consisting of letters, numbers, symbols, spaces, etc.
Reference: https://en.wikipedia.org/wiki/String-searching_algorithm
Synonym (EXACT): string-searching method evidence

(revised from what you proposed)
ECO:new 'regular expression method evidence'
Def: A type of string-matching evidence in which patterns consisting of characters and/or symbols in particular combinations and/or order are used to identify matches in a larger string or body of text.
Reference: https://en.wikipedia.org/wiki/Regular_expression
Synonym (EXACT): regex method evidence
Synonym (EXACT): regexp method evidence

ECO:new 'neural network method evidence'
Def: A type of machine learning method evidence in which the machine learning model consists of nodes connected to each other with edges that are organized into layers, where the edges can transmit signals between nodes such that the system acts similarly to biological neurons. 
Reference: https://en.wikipedia.org/wiki/Artificial_neural_network

**Revision to existing term:**
ECO:0008001 'deep learning neural network method evidence' (name revision)
Definition revision: A type of neural network method evidence which leverages a broad suite of neural network models, which use a combination of data attributes of an entity called features as inputs, and map them to outputs through multiple layers of connected hidden units, whose parameters are learned from data. In order to be considered deep, a neural network must have more than three layers.
New parent: ECO:new 'neural network method evidence'

**New structure:**
'computational evidence' ECO:0007672
--'machine learning method evidence' ECO:0008000
----'support vector machine evidence' (new)
----'neural network method evidence' (new)
------'deep learning neural network method evidence' ECO:0008001
--'string-matching method evidence' (new)
----'regular expression method evidence' (new)

Let me know if this all looks ok and we'll make the changes.

Best,
Michelle

**Comment by vanaukenk** [comment]
Thanks so much @mgiglio99 !

We have an Alliance literature metadata working group meeting tomorrow, so will review this ticket then and get back to you after that.

**Comment by vanaukenk** [comment]
@mgiglio99 

Thanks again for your help with the new ECO codes.

We reviewed your proposal on last Friday's Alliance working group call and everything looks good to us!

**Comment by nsuvarnaiari** [comment]
hi @vanaukenk 

The new ECO terms have been created and are released.
Here is the structure:
'computational evidence' ECO:0007672
--'machine learning method evidence' ECO:0008000
----'support vector machine evidence' ECO:0008010  (new)
----'neural network method evidence' ECO:0008013   (new)
------'deep learning neural network method evidence' ECO:0008001
--'string-matching method evidence'  ECO:0008011 (new)
----'regular expression method evidence' ECO:0008012 (new)

In addition, the name has been revised for 'deep learning neural network method evidence' ECO:0008001 (new name) and moved under the new parent 'neural network method evidence' ECO:0008013 (new).

| ECO_id      | ECO_label                                                       |
|-------------|-----------------------------------------------------------------|
| ECO:0008013 | neural network method evidence                                  |
| ECO:0008025 | neural network method evidence used in automatic assertion      |
| ECO:0008024 | neural network method evidence used in manual assertion         |
| ECO:0008012 | regular expression method evidence                              |
| ECO:0008023 | regular expression method evidence used in automatic assertion  |
| ECO:0008022 | regular expression method evidence used in manual assertion     |
| ECO:0008011 | string-matching method evidence                                 |
| ECO:0008021 | string-matching method evidence used in automatic assertion     |
| ECO:0008020 | string-matching method evidence used in manual assertion        |
| ECO:0008010 | support vector machine evidence                                 |
| ECO:0008019 | support vector machine evidence used in automatic assertion     |
| ECO:0008018 | support vector machine evidence used in manual assertion        |

Thanks,
Suvvi

**Comment by vanaukenk** [comment]
Thank you very much @nsuvarnaiari @mgiglio99 
We appreciate your help with the new terms!!
