### ISSUE TITLE
AmiGO API - seeking topology tree view example

### ISSUE THREAD

**Issue by dolleyj** [evidenceontology/evidenceontology#95]
I'm using the AmiGO API ([bbop-widget-set](https://github.com/berkeleybop/bbop-widget-set)) for an inferred tree view (topology_graph) of a selected term. My goal is to display it similar to this:

![screenshot_amigo_inferred_tree](https://cloud.githubusercontent.com/assets/6271039/14318532/41e8e752-fbdb-11e5-8423-a647f9920336.png)

I get the needed topology_graph_json, example below, but can't seem to find a widget for it. 

@cmungall , is there an AmiGO or bbop-js widget that generates the tree view? If so, where can I find an example?

Thanks!

topology_graph_json = 
`{"nodes":[{"id":"ECO:0000030","lbl":"BLAST evidence used in manual assertion"},{"id":"ECO:0000044","lbl":"sequence similarity evidence"},{"id":"ECO:0000209","lbl":"BLAST evidence used in automatic assertion"},{"id":"ECO:0000208","lbl":"protein BLAST evidence"},{"id":"ECO:0000041","lbl":"similarity evidence"},{"id":"ECO:0000206","lbl":"BLAST evidence"},{"id":"ECO:0000207","lbl":"nucleotide BLAST evidence"},{"id":"ECO:0005554","lbl":"pairwise sequence alignment evidence"},{"id":"ECO:0000000","lbl":"evidence"},{"id":"ECO:0000200","lbl":"sequence alignment evidence"}],"edges":[{"sub":"ECO:0000044","obj":"ECO:0000041","pred":"is_a"},{"sub":"ECO:0000041","obj":"ECO:0000000","pred":"is_a"},{"sub":"ECO:0005554","obj":"ECO:0000200","pred":"is_a"},{"sub":"ECO:0000208","obj":"ECO:0000206","pred":"is_a"},{"sub":"ECO:0000207","obj":"ECO:0000206","pred":"is_a"},{"sub":"ECO:0000209","obj":"ECO:0000206","pred":"is_a"},{"sub":"ECO:0000200","obj":"ECO:0000044","pred":"is_a"},{"sub":"ECO:0000030","obj":"ECO:0000206","pred":"is_a"},{"sub":"ECO:0000206","obj":"ECO:0005554","pred":"is_a"}]}`

**Comment by kltm** [comment]
tagging self on @kltm

**Comment by mchibucos** [comment]
Thanks @kltm !

**Comment by kltm** [comment]
You're likely thinking of something along the lines of: http://tomodachi.berkeleybop.org/amigo/browse ?
This widget did not happen to make the transition to the new toolset (as it was considered by many people icky).
I can go ahead and refresh that widget into the new set.

**Comment by kltm** [comment]
Also, thinking about this, depending on what you're trying to do there are a few approaches.
* If you're looking to browse, you can bookmark people into AmiGO right now: http://amigo.geneontology.org/amigo/term/ECO:0000000#display-lineage-tab (or similar)
* If you're wanting to embed in your own site and you are driving it off of your own golr instance, have you considered an amigo instance?
* If you're wanting to embed in your own site and are driving it off of the public amigo, then I should look to making the browse widget available in the new bbop-widget-set

**Comment by mchibucos** [comment]
Great ideas and questions. Our approach has been uncertain/exploratory thus far, but I can tell you our goals are twofold: 1. offer a nice visualization tool that allows users to see both graph (nodes connected by edges) and tree (preferably collapsable) views, as well as all relevant term information. 2. To use community tools so that we don't have to reinvent things and to hopefully offer a familiar interface to our users. AmiGO2 seems to offer both of these, more than other tools we've looked into yet. So we've been exploring the best way to go about this. Thank you for your helpful comments!

Embedding in our own site would probably be the best option, at least the one I had been hoping for initially. I would hope to potentially not display certain things like the Annotations tab, which might confuse ECO users who are not looking at us from the GO perspective. Not sure if that's possible or advisable.

I believe that @dolleyj was exploring driving off public AmiGO initially. But perhaps we should look into our own instance... So are there advantages/disadvantages to options number 2 & 3?

**Comment by kltm** [comment]
AmiGO itself is built largely on top of the bbop-widget-set and amigo2-instance-data information, with some other things here and there. Using these libs, the JS on any given page clusters around something like a very commenty and loose 200 LOC. Because we try to push as much as we can into reusable libraries, there is a lot designed to be spun and and be embeddable in other projects.

The one thing that is required is a GOlr (schema pattered Solr) instance to back things. In this case, if you were making frequent releases of ECO, you might not be in-sync with the GO releases that also brought in ECO (although we do try to have a decently frequent schedule); it might make sense in this case to run your own GOlr instance to back your widgets. Or, if having perfect control over your data was not an issue, simply aiming your widgets at our backend would be fine. This would be the difference between 2 and 3: extra overhead and machine requirements versus depending on somebody else's schedule.

While your own AmiGO instance may well be overkill, amigo is designed to let people plug in their own templates to get the UI more in line with what they want (e.g. http://dev.planteome.org/amigo versus http://tomodachi.berkeleybop.org/amigo/landing ). If what you want is completely different then what bending the amigo interface would offer, embedding is a good route. For example, Monarch Initiative's various embeddings (e.g. https://monarchinitiative.org/disease/DOID:65 , see the "Genes" tab as well ).

**Comment by mchibucos** [comment]
Excellent information. Let's think about this on our end and we'll likely ping you back at some point. Thanks again!

**Comment by kltm** [comment]
No problem. If you have any questions or would like quicker Q&A, I'm also available on skype, along with Chris.

**Comment by dolleyj** [comment]
Thank you for all the great feedback! I was looking to embed the widget running off  the public amigo.  We'll talk on our end given the options presented.  I'll be in touch.

**Comment by dolleyj** [comment]
After some discussion, we're decided (for now) to pursue an embedded widget running off the public amigo.
 @kltm , would it be possible for you to make the browse widget available in the new bbop-widget-set?

**Comment by kltm** [comment]
Go ahead and subscribe to the above issue for progress.

**Comment by rctauber** [comment]
Reopen if this is still an issue, but it seems to be resolved.
